#!/usr/bin/env python3
"""Architecture C duel sim v9 — scene combat chassis + duel context layer."""  # [canonical: N/A]
import numpy as np  # [canonical: N/A]
from collections import defaultdict  # [canonical: N/A]

# [canonical: params/core.md §dice engine — d10 pool TN system, 1s subtract, 10s chain]
def roll(rng, n, tn):
    if n <= 0: return 0  # [canonical: N/A — floor]
    d = rng.integers(1, 11, size=n)  # [canonical: params/core.md §dice engine]
    h = int(np.sum(d >= tn)) - int(np.sum(d == 1))  # [canonical: params/core.md — hits minus 1s]
    t = int(np.sum(d == 10))  # [canonical: params/core.md — chain on 10]
    if t > 0: h += int(np.sum(rng.integers(1, 11, size=t) >= tn))  # [canonical: params/core.md — chain]
    return max(0, h)  # [canonical: N/A — floor]

# [canonical: params/combat.md §Damage Formula PP-232 — weapon modifier vs armour tier]
WMOD = {  # [canonical: params/combat.md §Damage Formula PP-232]
    'LB': {'None': 3, 'Light': 2, 'Medium': 1, 'Heavy': 0},  # [canonical: params/combat.md §Damage Formula]
    'HB': {'None': 6, 'Light': 4, 'Medium': 2, 'Heavy': 0},  # [canonical: params/combat.md §Damage Formula]
    'LN': {'None': 3, 'Light': 3, 'Medium': 3, 'Heavy': 3},  # [canonical: params/combat.md §Damage Formula]
    'HN': {'None': 5, 'Light': 5, 'Medium': 5, 'Heavy': 5},  # [canonical: params/combat.md §Damage Formula]
}

# [canonical: params/combat.md §Weapon System PP-232]
WEAPONS = {  # [canonical: params/combat.md §Weapon System PP-232]
    'dagger':     (5, 'LB'),  # [canonical: params/combat.md §Weapon System — Short Light Blade TN5]
    'arming':     (6, 'HB'),  # [canonical: params/combat.md §Weapon System — Short Heavy Blade TN6]
    'longsword':  (7, 'HB'),  # [canonical: params/combat.md §Weapon System — Long Heavy Blade TN7]
    'mace':       (7, 'LN'),  # [canonical: params/combat.md §Weapon System — Short Heavy Blunt TN7]
    'warhammer':  (8, 'HN'),  # [canonical: params/combat.md §Weapon System — Long Heavy Blunt TN8]
    'staff':      (7, 'LN'),  # [canonical: params/combat.md §Weapon System — Long Light Blunt TN7]
    'spear':      (6, 'LB'),  # [canonical: params/combat.md §Weapon System — Long Light Blade TN6]
}

# [canonical: params/combat.md §Pool Formula L14]
def mk_pool(agi, hist): return max(5, agi * 2 + hist + 3)  # [canonical: params/combat.md §Pool Formula]

# [canonical: designs/scene/derived_stats_v30.md §4.1 PP-716]
def mk_wi(end): return end + 6  # [canonical: designs/scene/derived_stats_v30.md §4.1]
def mk_mw(end): return end // 2 + 1  # [canonical: designs/scene/derived_stats_v30.md §4.1]
def mk_hp(end): return mk_wi(end) * (mk_mw(end) + 1)  # [canonical: designs/scene/derived_stats_v30.md §4.1]

# [canonical: N/A — Architecture C flat stamina, replaces canonical End*5 for duels]
def mk_stam(end): return 15 + end * 2  # [canonical: N/A — C-specific flat stamina]

RATTLE_MAX = 2  # [canonical: N/A — free-rider taunt cumulative cap]
TAUNT_CD = 2  # [canonical: N/A — taunt cooldown rounds]

def pick(prot, pool, sf, wounds, has_init, cog,  # [canonical: N/A — protocol]
         op, osf, ohf, ofd, rd, tcd, arena, rat,  # [canonical: N/A]
         oa=None, osp=None):  # [canonical: N/A — opponent action/split if visible]
    def ss(sp, twt=False):  # [canonical: N/A — helper]
        return ('stunt_strike' if arena > 0 else 'strike', sp, twt)  # [canonical: N/A]

    # Protocol non-strike actions (priority over reactive layer)
    if prot == 'FEINTER':  # [canonical: N/A — test protocol]
        if rd % 3 == 1: return ('feint', 0.55, False)  # [canonical: N/A]
    if prot in ('STAMINA_FIGHTER', 'ADAPTIVE', 'DUELLIST'):  # [canonical: N/A]
        if sf < 0.2: return ('breath', 0.0, False)  # [canonical: N/A]
    if prot == 'GUARD': return ('guard', 0.0, False)  # [canonical: designs/scene/combat_v30.md §4]

    # Reactive layer — second declarer sees opponent commit
    # [canonical: designs/scene/combat_v30.md §3 — initiative holder declares last]
    if oa is not None and prot in ('ADAPTIVE', 'DUELLIST', 'COUNTER_PUNCHER'):  # [canonical: N/A]
        if oa == 'breath': return ss(0.80)  # [canonical: N/A — free damage]
        if oa == 'feint': return ss(0.75)  # [canonical: N/A — punish commit]
        if oa == 'guard':  # [canonical: N/A]
            if sf > 0.4: return ('feint', 0.55, False)  # [canonical: N/A — setup vs turtle]
            return ss(0.45)  # [canonical: N/A]
        if oa in ('strike', 'stunt_strike') and osp is not None:  # [canonical: N/A]
            twt = (prot == 'DUELLIST' and tcd == 0)  # [canonical: N/A — taunt with strike]
            if osp >= 0.65: return ss(0.30, twt)  # [canonical: N/A — absorb high commit]
            if osp <= 0.35: return ss(0.70, twt)  # [canonical: N/A — punish passivity]
            return ss(0.55, twt)  # [canonical: N/A]

    # Base protocols
    if prot == 'AGGRESSIVE': return ('strike', 0.75, False)  # [canonical: N/A — test protocol]
    if prot == 'DEFENSIVE': return ('strike', 0.30, False)  # [canonical: N/A — test protocol]
    if prot == 'BALANCED': return ('strike', 0.50, False)  # [canonical: N/A — test protocol]
    if prot == 'FEINTER': return ss(0.60)  # [canonical: N/A — test protocol]
    if prot == 'STAMINA_FIGHTER': return ('strike', 0.30, False)  # [canonical: N/A — test protocol]
    if prot == 'COUNTER_PUNCHER':  # [canonical: N/A — test protocol]
        if ofd > 0 or ohf < 0.4: return ss(0.65)  # [canonical: N/A]
        return ('strike', 0.30, False)  # [canonical: N/A]
    if prot == 'ADAPTIVE':  # [canonical: N/A — test protocol]
        if ofd > 0: return ss(0.70)  # [canonical: N/A]
        if ohf < 0.3: return ss(0.75)  # [canonical: N/A]
        if has_init and rd % 4 == 0: return ('feint', 0.50, False)  # [canonical: N/A]
        return ss(0.50)  # [canonical: N/A]
    if prot == 'DUELLIST':  # [canonical: N/A — test protocol]
        twt = (tcd == 0)  # [canonical: N/A — taunt when off cooldown]
        if ofd > 0: return ss(0.65, twt)  # [canonical: N/A]
        if ohf < 0.3: return ss(0.75, twt)  # [canonical: N/A]
        if has_init: return ss(0.55, twt)  # [canonical: N/A]
        return ss(0.50, twt)  # [canonical: N/A]
    return ('strike', 0.50, False)  # [canonical: N/A — fallback]

def sim_duel(w_a='arming', w_b='arming', arm_a='None', arm_b='None',  # [canonical: N/A — sim]
             agi_a=4, agi_b=4, str_a=4, str_b=4, end_a=4, end_b=4,  # [canonical: N/A — test stats]
             cog_a=4, cog_b=4, comp_a=5, comp_b=5, hist=2,  # [canonical: N/A — test stats]
             prot_a='ADAPTIVE', prot_b='ADAPTIVE', arena=0,  # [canonical: N/A]
             seed=42, maxr=30):  # [canonical: N/A — sim params]
    rng = np.random.default_rng(seed)  # [canonical: N/A — RNG]
    tna, wca = WEAPONS[w_a]; tnb, wcb = WEAPONS[w_b]  # [canonical: params/combat.md §Weapon System]
    pa, pb = mk_pool(agi_a, hist), mk_pool(agi_b, hist)  # [canonical: params/combat.md §Pool Formula]
    sa, sb = mk_stam(end_a), mk_stam(end_b)  # [canonical: N/A — C flat stamina]
    ha, hb = mk_hp(end_a), mk_hp(end_b)  # [canonical: designs/scene/derived_stats_v30.md §4.1]
    wia, wib = mk_wi(end_a), mk_wi(end_b)  # [canonical: designs/scene/derived_stats_v30.md §4.1]
    mwa, mwb = mk_mw(end_a), mk_mw(end_b)  # [canonical: designs/scene/derived_stats_v30.md §4.1]
    sma, smb = sa, sb  # [canonical: N/A]
    wact, wbct = 0, 0  # [canonical: N/A — wound counts]
    daa, dab = 0, 0  # [canonical: N/A — damage accumulators]
    # [canonical: params/combat.md §Initiative PP-232 — higher Agi acts last]
    if agi_a > agi_b: init_a = True  # [canonical: params/combat.md §Initiative PP-232]
    elif agi_b > agi_a: init_a = False  # [canonical: params/combat.md §Initiative PP-232]
    else: init_a = bool(rng.integers(0, 2))  # [canonical: params/combat.md §PP-239 — tiebreak random]
    fda, fdb = 0, 0  # [canonical: params/combat.md §PP-294 — feint debuff]
    rat_a, rat_b = 0, 0  # [canonical: N/A — rattled from taunt]
    ooa = oob = False  # [canonical: designs/scene/combat_v30.md §7 — OOB]
    tca, tcb = 0, 0  # [canonical: N/A — taunt cooldown]
    L = defaultdict(int)  # [canonical: N/A — log]

    def ep(base, w, fd, oo, rat):  # [canonical: params/combat.md §Pool Formula]
        p = base - w - fd - rat  # [canonical: params/combat.md — wound -1D, feint debuff, rattled]
        if oo: p -= 2  # [canonical: designs/scene/combat_v30.md §1 — OOB -2D]
        return max(5, p)  # [canonical: params/combat.md §Pool Formula — minimum 5 ED-203]

    for rd in range(1, maxr + 1):  # [canonical: N/A — sim loop]
        # End checks  # [canonical: designs/scene/combat_v30.md §4 — Stage 1]
        ai = wact > mwa or ha <= 0  # [canonical: designs/scene/derived_stats_v30.md §4.1]
        bi = wbct > mwb or hb <= 0  # [canonical: designs/scene/derived_stats_v30.md §4.1]
        if ai and bi: L.update(rd=rd-1, w='draw', e='mi'); break  # [canonical: N/A]
        if ai: L.update(rd=rd-1, w='B', e='iA'); break  # [canonical: N/A]
        if bi: L.update(rd=rd-1, w='A', e='iB'); break  # [canonical: N/A]
        # E7 yield  # [canonical: N/A — Architecture C]
        if ooa and oob: L.update(rd=rd, w='A' if ha > hb else ('B' if hb > ha else 'draw'), e='my'); break  # [canonical: N/A]
        if ooa: L.update(rd=rd, w='B', e='yA'); break  # [canonical: N/A]
        if oob: L.update(rd=rd, w='A', e='yB'); break  # [canonical: N/A]

        Pa = ep(pa, wact, fda, ooa, rat_a)  # [canonical: params/combat.md §Pool Formula]
        Pb = ep(pb, wbct, fdb, oob, rat_b)  # [canonical: params/combat.md §Pool Formula]
        sfa, sfb = sa / max(1, sma), sb / max(1, smb)  # [canonical: N/A]
        ohfa = ha / max(1, mk_hp(end_a))  # [canonical: N/A]
        ohfb = hb / max(1, mk_hp(end_b))  # [canonical: N/A]

        # Declaration order  # [canonical: designs/scene/combat_v30.md §3]
        a1 = not init_a  # [canonical: designs/scene/combat_v30.md §3 — lower init first]
        b1 = init_a  # [canonical: designs/scene/combat_v30.md §3]
        if a1 and not b1:  # [canonical: N/A]
            aa, spa, ta = pick(prot_a, Pa, sfa, wact, init_a, cog_a, Pb, sfb, ohfb, fdb, rd, tca, arena, rat_a)  # [canonical: N/A]
            ab, spb, tb = pick(prot_b, Pb, sfb, wbct, not init_a, cog_b, Pa, sfa, ohfa, fda, rd, tcb, arena, rat_b, aa, spa)  # [canonical: N/A]
        elif b1 and not a1:  # [canonical: N/A]
            ab, spb, tb = pick(prot_b, Pb, sfb, wbct, not init_a, cog_b, Pa, sfa, ohfa, fda, rd, tcb, arena, rat_b)  # [canonical: N/A]
            aa, spa, ta = pick(prot_a, Pa, sfa, wact, init_a, cog_a, Pb, sfb, ohfb, fdb, rd, tca, arena, rat_a, ab, spb)  # [canonical: N/A]
        else:  # [canonical: N/A]
            aa, spa, ta = pick(prot_a, Pa, sfa, wact, init_a, cog_a, Pb, sfb, ohfb, fdb, rd, tca, arena, rat_a)  # [canonical: N/A]
            ab, spb, tb = pick(prot_b, Pb, sfb, wbct, not init_a, cog_b, Pa, sfa, ohfa, fda, rd, tcb, arena, rat_b)  # [canonical: N/A]

        # Pool splits  # [canonical: designs/scene/combat_v30.md §3]
        if aa == 'guard': oa, dda = 0, Pa  # [canonical: designs/scene/combat_v30.md §4 — Full Guard]
        else: oa = max(1, int(Pa * spa)); dda = Pa - oa  # [canonical: designs/scene/combat_v30.md §3]
        if ab == 'guard': ob, ddb = 0, Pb  # [canonical: designs/scene/combat_v30.md §4]
        else: ob = max(1, int(Pb * spb)); ddb = Pb - ob  # [canonical: designs/scene/combat_v30.md §3]

        nfa = nfb = 0  # [canonical: N/A]
        nda = ndb = 0  # [canonical: N/A]
        sta = arena if aa == 'stunt_strike' else 0  # [canonical: designs/scene/combat_v30.md §4 Stunt]
        stb = arena if ab == 'stunt_strike' else 0  # [canonical: designs/scene/combat_v30.md §4 Stunt]

        # P1: Strike  # [canonical: designs/scene/combat_v30.md §4 — Strike]
        if aa in ('strike', 'stunt_strike'):  # [canonical: designs/scene/combat_v30.md §4]
            h = roll(rng, oa + sta, tna); bl = roll(rng, ddb, tnb)  # [canonical: params/core.md §dice engine]
            net = h - bl  # [canonical: params/combat.md §Damage Formula]
            if net > 0:  # [canonical: params/combat.md §Damage Formula]
                wm = WMOD[wca][arm_b]  # [canonical: params/combat.md §Damage Formula]
                if net >= 3: wm *= 2  # [canonical: params/combat.md §Damage Formula — crit]
                d = net + str_a + wm  # [canonical: params/combat.md §Damage Formula]
                hb = max(0, hb - d)  # [canonical: N/A — floor]
                dab += d  # [canonical: designs/scene/derived_stats_v30.md §4.1]
                wbct = min(mwb + 1, dab // wib)  # [canonical: designs/scene/derived_stats_v30.md §4.1]
                nda = d  # [canonical: N/A]
            cost = 5 + (1 if sta else 0) + (1 if ta else 0)  # [canonical: designs/scene/combat_v30.md §7 — action cost 5 + stunt +1 + taunt +1]
            sa = max(0, sa - cost)  # [canonical: designs/scene/combat_v30.md §7]

        if ab in ('strike', 'stunt_strike'):  # [canonical: designs/scene/combat_v30.md §4]
            h = roll(rng, ob + stb, tnb); bl = roll(rng, dda, tna)  # [canonical: params/core.md §dice engine]
            net = h - bl  # [canonical: params/combat.md §Damage Formula]
            if net > 0:  # [canonical: params/combat.md §Damage Formula]
                wm = WMOD[wcb][arm_a]  # [canonical: params/combat.md §Damage Formula]
                if net >= 3: wm *= 2  # [canonical: params/combat.md §Damage Formula — crit]
                d = net + str_b + wm  # [canonical: params/combat.md §Damage Formula]
                ha = max(0, ha - d)  # [canonical: N/A — floor]
                daa += d  # [canonical: designs/scene/derived_stats_v30.md §4.1]
                wact = min(mwa + 1, daa // wia)  # [canonical: designs/scene/derived_stats_v30.md §4.1]
                ndb = d  # [canonical: N/A]
            cost = 5 + (1 if stb else 0) + (1 if tb else 0)  # [canonical: designs/scene/combat_v30.md §7]
            sb = max(0, sb - cost)  # [canonical: designs/scene/combat_v30.md §7]

        # P2: Feint (PP-294 — defense retained)  # [canonical: designs/scene/combat_v30.md §4 PP-294]
        if aa == 'feint':  # [canonical: params/combat.md §PP-294]
            fn = max(3, oa)  # [canonical: params/combat.md §PP-294 — minimum 3]
            dda = max(0, Pa - fn)  # [canonical: designs/scene/combat_v30.md §4 PP-294 — remainder to defense]
            fh = roll(rng, fn, 7); od = roll(rng, ddb, 7)  # [canonical: params/combat.md §PP-294 — TN 7]
            if fh > od: nfb = fh - od; L['fl'] += 1  # [canonical: params/combat.md §PP-294 — margin]
            sa = max(0, sa - 5)  # [canonical: designs/scene/combat_v30.md §7]
        if ab == 'feint':  # [canonical: params/combat.md §PP-294]
            fn = max(3, ob)  # [canonical: params/combat.md §PP-294]
            ddb = max(0, Pb - fn)  # [canonical: designs/scene/combat_v30.md §4 PP-294]
            fh = roll(rng, fn, 7); od = roll(rng, dda, 7)  # [canonical: params/combat.md §PP-294]
            if fh > od: nfa = fh - od; L['fl'] += 1  # [canonical: params/combat.md §PP-294]
            sb = max(0, sb - 5)  # [canonical: designs/scene/combat_v30.md §7]

        # Reactive: Breath  # [canonical: designs/scene/combat_v30.md §4 — Take a Breath]
        if aa == 'breath': sa = min(sma, sa + (end_a + hist) * 2)  # [canonical: designs/scene/combat_v30.md §7 — (End+hist)x2]
        if ab == 'breath': sb = min(smb, sb + (end_b + hist) * 2)  # [canonical: designs/scene/combat_v30.md §7]

        # Free-rider Taunt: COG vs Composure, cumulative -1D, cap RATTLE_MAX  # [canonical: N/A — duel action]
        if ta and tca == 0 and aa in ('strike', 'stunt_strike'):  # [canonical: N/A]
            if roll(rng, cog_a, 7) > roll(rng, comp_b, 7):  # [canonical: N/A — COG vs Composure TN 7]
                rat_b = min(RATTLE_MAX, rat_b + 1)  # [canonical: N/A — cumulative rattled]
                L['tl'] += 1  # [canonical: N/A — log]
            tca = TAUNT_CD  # [canonical: N/A — cooldown]
        if tb and tcb == 0 and ab in ('strike', 'stunt_strike'):  # [canonical: N/A]
            if roll(rng, cog_b, 7) > roll(rng, comp_a, 7):  # [canonical: N/A]
                rat_a = min(RATTLE_MAX, rat_a + 1)  # [canonical: N/A]
                L['tl'] += 1  # [canonical: N/A]
            tcb = TAUNT_CD  # [canonical: N/A]

        if aa == 'guard': sa = max(0, sa - 3)  # [canonical: designs/scene/combat_v30.md §7 — defensive 3]
        if ab == 'guard': sb = max(0, sb - 3)  # [canonical: designs/scene/combat_v30.md §7]

        # Initiative transfer  # [canonical: designs/scene/combat_v30.md §3]
        if nda > 0 and ndb == 0: init_a = True  # [canonical: designs/scene/combat_v30.md §3]
        elif ndb > 0 and nda == 0: init_a = False  # [canonical: designs/scene/combat_v30.md §3]

        fda = nfa; fdb = nfb  # [canonical: params/combat.md §PP-294 — next round]
        ooa = sa <= 0; oob = sb <= 0  # [canonical: designs/scene/combat_v30.md §7 — OOB]
        tca = max(0, tca - 1); tcb = max(0, tcb - 1)  # [canonical: N/A — cooldown tick]
    else:
        L.update(rd=maxr, w='A' if ha > hb else ('B' if hb > ha else 'draw'), e='t')  # [canonical: N/A]

    L['a_w'] = wact; L['b_w'] = wbct  # [canonical: N/A — log]
    L['a_s'] = sa; L['b_s'] = sb  # [canonical: N/A]
    L['b_rat'] = rat_b; L['a_rat'] = rat_a  # [canonical: N/A]
    return L  # [canonical: N/A]
