"""
Unit tests for tools/vocab_store.py — the Phase-3 vocabulary fold (ED-IN-0078).

Pins the fold's guarantees: the committed register views equal a fresh render from
vocab_source.yaml (parity), and the source carries every folded register's data.
Runs against the live working tree.
"""
import os
import sys

HERE = os.path.dirname(__file__)
TOOLS = os.path.join(HERE, '..', '..', 'tools')
sys.path.insert(0, TOOLS)
import vocab_store as vs  # noqa: E402


def test_views_match_source_parity():
    """Every committed register view == fresh render from vocab_source.yaml.
    If this fails: run `python tools/vocab_store.py --build` and commit."""
    ok, msgs = vs.check()
    assert ok, "vocab view drift:\n" + "\n".join(msgs)


def test_source_carries_every_folded_register():
    regs = vs._load_source()
    for name in vs.REGISTERS:
        assert name in regs and regs[name], f"vocab_source.yaml missing register block: {name}"


def test_views_are_generated_stamped():
    """Each folded register file must carry the GENERATED header (it is a view, not hand-authored)."""
    for name, path in vs.REGISTERS.items():
        head = path.read_text(encoding='utf-8')[:200]
        assert 'GENERATED by tools/vocab_store.py' in head, f"{name} view missing GENERATED header"


def test_frozen_mirror_matches_and_is_untouched():
    """name_collision is DUPLICATED, not folded (OPT-AV-14 preserved): the frozen file must NOT
    carry the GENERATED stamp, and its data must match the queryable mirror in vocab_source."""
    regs = vs._load_source()
    for name, path in vs.FROZEN_MIRRORS.items():
        assert name in regs, f"vocab_source missing frozen-mirror block: {name}"
        assert 'GENERATED by tools/vocab_store.py' not in path.read_text(encoding='utf-8')[:200], \
            f"{name} frozen file must stay hand-authored (OPT-AV-14) — not a generated view"
        assert vs._frozen_data(path) == regs[name], f"mirror {name} drifted from the frozen file"
