"""Every module-level path constant in `tools/` must resolve in the working tree (ED-IN-0122).

WHY THIS EXISTS — a pattern defect caught twice in two days, fixed twice as a one-off, guarded
zero times:

  * 2026-08-01: `canon_coverage_check.DESIGNS_DIR = os.path.join(_REPO_ROOT, 'designs')`. `designs/`
    was retired 2026-07-19 (ED-IN-0071 P4/P5). `os.walk` on a missing directory yields nothing
    rather than raising, so the tool reported **0 findings against a 130-path registry, under
    `--strict`, for 13 days**. Repointed to `systems/` — no guard written.
  * 2026-08-02: `ci_formula_prose_check.DEFAULT_CENSUS` pointed at
    `designs/audit/2026-07-08-.../quantity_census.yaml`. The census moved with the rest of the
    `designs/audit/` corpus in the same retirement. `load_census()` returned `[]` on the missing
    file and the report rendered "_No formula prose-drift found in scope._" for 14 days. Pointed at
    the live path it scans 88 rows and finds 14 CENSUS_DRIFT.

This is the CLAUDE.md §0.1 point-5 signature verbatim: *the broken code was correct when written and
stopped working because something else changed*. The prescribed answer is one owner, every site
routed through it, and **a guard that fails on recurrence — "if you cannot write the guard you have
not understood the pattern."** Two repoints without a guard is the pattern going unlearned.

WHY THE GUARD IS SHAPED THIS WAY. The tempting version scans for the RETIRED tree names
(`designs/`, `sim/`) and fails on a match. That guard is already obsolete when written: it protects
against the last restructure, not the next one, and this corpus restructures continually
(ED-IN-0071 alone retired two top-level trees and rehomed ten subsystems). The invariant that
actually holds is direction-free — **a tool's declared input path must exist** — so the scan is
automatic over the AST rather than a curated list of bad prefixes. A newly-added constant inherits
the guard with no edit here, which is the property `ci_common.sim_reference_roots()`'s glob has and
a hardcoded roster never does.

Comments and docstrings are invisible to this check *by construction*, not by filtering: they are
not in the parsed statement tree. That matters because `tools/` carries dozens of legitimate prose
citations of `designs/...` paths, which CLAUDE.md §3 explicitly says resolve via
`references/restructure_ledger.md`'s alias map and must NOT be rewritten. An AST walk separates
"the path this tool reads" from "the path this tool talks about" for free; a grep cannot.

MEASURED AT INTRODUCTION: 5 candidate constants across `tools/**/*.py` failed a naive existence
probe, 4 of them spuriously (glob constants like `workplans/POINTER_*.md`, where the literal string
is never a real path and the DIRECTORY of its non-magic prefix is what must exist). With the probe
corrected, exactly one remains — `review_core.STATE_PATH`, a generated OUTPUT — so this lands green
on a single documented exemption rather than importing a backlog into a blocking gate
(CLAUDE.md §0.1 point 5 on the real cost of widening scope).
"""
import ast
import glob
import os

import pytest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))

# A constant is only treated as a path if its first segment is a real top-level tree. This is what
# keeps `ci_program_claim_check.TREES` and friends out of scope: those hold BARE tree names
# ('designs', 'sim') as recognizer tokens with no separator, and they are *supposed* to still name
# retired trees so that dead paths can be identified and reported.
TREES = (
    'designs', 'sim', 'systems', 'engine', 'references', 'params', 'tests', 'registers', 'canon',
    'audit', 'arcs', 'godot', 'tools', 'skills', 'proposals', 'workplans', 'deprecated',
    'dashboard', '.github', '.claude',
)

# Constants naming an artifact the tool WRITES rather than reads. An output legitimately does not
# exist before its first run, so requiring it to resolve would fail on a clean checkout. Keyed by
# (module basename, constant) so a rename cannot silently widen the exemption, and each entry
# carries the reason — adding one is meant to be a deliberate act, not a convenient escape.
OUTPUT_PATHS = {
    ('review_core.py', 'STATE_PATH'):
        'generated by `review_core.py --json`; absent on a clean checkout by design',
}


def _repoish(node):
    """True if `node` is a Name that plainly denotes the repository root."""
    return isinstance(node, ast.Name) and ('REPO' in node.id.upper() or 'ROOT' in node.id.upper())


def _literal_path(node):
    """Reduce a path-ish expression to a repo-relative string, or None if not reducible.

    Handles the three shapes the corpus actually uses — a bare string literal, `os.path.join(...)`,
    and `Path(...) / 'x'` division chains — and deliberately gives up on anything else rather than
    guessing. A missed constant is a smaller harm than a fabricated one: `test_scan_is_not_vacuous`
    below is what keeps "gives up" from quietly becoming "matches nothing".
    """
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.Call):
        fn = node.func
        name = fn.attr if isinstance(fn, ast.Attribute) else getattr(fn, 'id', None)
        if name == 'join':
            parts = []
            for arg in node.args:
                if isinstance(arg, ast.Constant) and isinstance(arg.value, str):
                    parts.append(arg.value)
                elif _repoish(arg):
                    parts.append('<ROOT>')
                else:
                    return None
            return '/'.join(parts)
        return None
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Div):
        left = '<ROOT>' if _repoish(node.left) else _literal_path(node.left)
        right = _literal_path(node.right)
        if left and right:
            return left + '/' + right
    return None


# A constant whose NAME declares it a path is in scope whatever its value looks like. This is the
# second discriminator, and mutation testing is what proved it necessary: the TREES head-gate below
# can only recognize a value that still points somewhere plausible, so a constant repointed to a
# typo (`AUDIT_DIR = 'audits'`) or to a tree that does not exist at all falls straight through it —
# which is the exact failure being guarded against. Naming is the more reliable signal precisely
# because it survives the value going wrong.
PATH_NAME_SUFFIXES = ('_DIR', '_PATH', '_GLOB', '_FILE', '_ROOT', '_MD', '_YAML', '_JSON', '_JSONL')


def _declares_path(name, node, declared):
    """True if this constant should be treated as a filesystem path."""
    if name.endswith(PATH_NAME_SUFFIXES):
        return True
    # A path-CONSTRUCTION expression is unambiguous regardless of the resulting string.
    if isinstance(node, (ast.Call, ast.BinOp)):
        return True
    return declared.split('/')[0] in TREES


def _probe(rel):
    """The deepest ancestor of `rel` that must exist on disk.

    For a glob, the literal string is never a path — `workplans/POINTER_*.md` names no file — so the
    thing to check is the directory containing the non-magic prefix. Getting this wrong is what
    produced 4 of the 5 initial false positives, and a guard with a 80% false-positive rate gets
    switched off long before it catches anything.
    """
    if any(ch in rel for ch in '*?['):
        prefix = rel.split('*')[0].split('?')[0].split('[')[0]
        rel = prefix if prefix.endswith('/') else os.path.dirname(prefix)
    return rel.rstrip('/')


def _path_constants():
    """[(module_rel, const_name, declared, probe)] for every module-level path constant."""
    found = []
    for path in sorted(glob.glob(os.path.join(ROOT, 'tools', '**', '*.py'), recursive=True)):
        rel_mod = os.path.relpath(path, ROOT).replace(os.sep, '/')
        try:
            tree = ast.parse(open(path, encoding='utf-8').read())
        except SyntaxError:
            continue  # py_compile is the gate for that; not this test's job to double-report it
        for node in tree.body:
            if not isinstance(node, ast.Assign):
                continue
            names = [t.id for t in node.targets if isinstance(t, ast.Name) and t.id.isupper()]
            if not names:
                continue
            declared = _literal_path(node.value)
            if not declared:
                continue
            declared = declared.replace('<ROOT>/', '').replace('<ROOT>', '')
            # NOTE: single-segment constants (`SYSTEMS_DIR = os.path.join(_REPO_ROOT, 'systems')`)
            # are IN scope. An earlier draft required a '/' separator to avoid matching bare
            # tree-name tokens, and mutation testing killed it: that filter excluded
            # `canon_coverage_check.DESIGNS_DIR = os.path.join(_REPO_ROOT, 'designs')` — the very
            # 13-day blind gate this guard is named after. The bare-token worry was unfounded
            # anyway; recognizer rosters like `ci_program_claim_check.TREES` are tuple literals,
            # never an UPPER Name bound to a reducible path expression. Measured: admitting them
            # adds 5 constants, all real paths, all resolving — zero false positives.
            if not _declares_path(names[0], node.value, declared):
                continue
            found.append((rel_mod, names[0], declared, _probe(declared)))
    return found


def _shape_counts():
    """{shape: n} over the scanned constants — the input to the anti-vacuity floor below."""
    counts = {'literal': 0, 'constructed': 0, 'glob': 0}
    for _mod, _const, declared, _probe_ in _path_constants():
        counts['glob' if any(c in declared for c in '*?[') else 'literal'] += 1
        if '/' in declared:
            counts['constructed'] += 1
    return counts


def test_scan_is_not_vacuous():
    """Guards the guard.

    The parametrized test below is generated from `_path_constants()`. If the AST walk ever stops
    matching — a refactor to `pathlib`-only constants, an `ast` API change, a bad glob — it yields
    an empty list, pytest generates zero cases, and the suite goes green over an unrun check. That
    is precisely the "gate reporting clean over nothing" failure this module exists to prevent, so
    it would be absurd to leave this file open to it (CLAUDE.md §0.1 point 2: an assertion must be
    able to observe the failure it excludes).

    A total-count floor alone is NOT enough, and mutation testing is how that was established:
    crippling `_literal_path`'s string-literal branch still left 32 constants — comfortably over an
    earlier floor of 20 — so half the scan died green. The floors are therefore per-SHAPE, because
    each shape is recognized by a different branch and a branch can rot on its own.
    """
    consts = _path_constants()
    shapes = _shape_counts()
    assert len(consts) >= 55, (
        f'only {len(consts)} module-level path constant(s) found across tools/**/*.py (expected '
        f'~65) — the AST walk has stopped matching, so the cases below are largely vacuous. Fix '
        f'_literal_path(), do not lower this floor.')
    for shape, floor in (('literal', 40), ('constructed', 30), ('glob', 5)):
        assert shapes[shape] >= floor, (
            f'only {shapes[shape]} constant(s) of shape {shape!r} (floor {floor}) — that branch of '
            f'_literal_path()/_declares_path() has stopped recognizing its inputs, which makes '
            f'those cases silently disappear rather than fail. Repair the branch.')


@pytest.mark.parametrize(
    'mod,const,declared,probe', _path_constants(),
    ids=lambda v: v if isinstance(v, str) else str(v))
def test_path_constant_resolves(mod, const, declared, probe):
    key = (os.path.basename(mod), const)
    if key in OUTPUT_PATHS:
        pytest.skip(f'{const} is a generated output: {OUTPUT_PATHS[key]}')
    assert os.path.exists(os.path.join(ROOT, probe)), (
        f'{mod} declares {const} = {declared!r}, which does not resolve (checked {probe!r}).\n'
        f'A tool whose input path is gone does not report "nothing found" — it reports nothing, '
        f'indistinguishably. Two gates ran blind for 13 and 14 days on exactly this.\n'
        f'Fix by REPOINTING the constant at the live path (resolve it via '
        f'references/restructure_ledger.md if the tree was restructured). If this constant names '
        f'an artifact the tool WRITES, add it to OUTPUT_PATHS above with the reason.')
