-- valoria_index.sql
-- Schema + curated data for Valoria file index.
-- Last updated: 2026-05-08T01:21:51Z
-- Generated tables (files, entities, entity_aliases) are rebuilt at
-- session start by tools/regenerate_file_index.py — never hand-edit those.
-- Curated tables (concepts, aliases, concept_files) are safe to edit here.

-- ── Schema ─────────────────────────────────────────────────────────────────
-- valoria_index.sql
-- Valoria file index + concept alias system.
-- Generated by tools/regenerate_file_index.py
-- Loaded at bootstrap into /home/claude/valoria.db
-- Human-editable: concepts, aliases, concept_files rows.
-- Machine-managed: files rows (regenerator owns these).

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- ── Meta ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL DEFAULT ''
);
INSERT OR IGNORE INTO meta VALUES ('version',     '1');
INSERT OR IGNORE INTO meta VALUES ('generated',   '');   -- ISO timestamp of last regen
INSERT OR IGNORE INTO meta VALUES ('ttrpg_sha',   '');   -- HEAD sha at last regen
INSERT OR IGNORE INTO meta VALUES ('file_count',  '0');  -- active file count


-- ── Files ─────────────────────────────────────────────────────────────────────
-- Machine-managed. Regenerator owns all rows.
-- status: active = in service; deprecated = superseded; archived = session logs etc.
-- variant: normal = full prose doc; index = auto-generated heading table (_index.md);
--          infill = supplementary prose (_infill.md); compiled = merged output;
--          data = yaml/json param; tool = python script; other = everything else.

CREATE TABLE IF NOT EXISTS files (
  path      TEXT PRIMARY KEY,
  directory TEXT NOT NULL,
  filename  TEXT NOT NULL,
  status    TEXT NOT NULL DEFAULT 'active',   -- active | deprecated | archived | pending-prioritization | ...
  variant   TEXT          DEFAULT 'other',     -- normal | index | infill | compiled | data | tool | skill | test | other
  pair_id   TEXT,    -- groups _v30 / _index / _infill under one logical doc
  domain    TEXT,    -- world | territory | scene | provincial | arcs | npcs |
                     -- threadwork | ui | audit | architecture | canon |
                     -- references | skills | tools | params | tests | root
  sha       TEXT,    -- git blob sha — used by regenerator for incremental updates
  headings  TEXT     -- tab-separated H1..H3 text extracted from content
);

CREATE INDEX IF NOT EXISTS idx_files_status_domain ON files(status, domain);
CREATE INDEX IF NOT EXISTS idx_files_pair           ON files(pair_id);
CREATE INDEX IF NOT EXISTS idx_files_variant        ON files(status, variant);


-- ── Concepts ──────────────────────────────────────────────────────────────────
-- Human-curated. Populated by mining pass and manually extended.
-- Each concept is a topic that maps to one or more files.

CREATE TABLE IF NOT EXISTS concepts (
  id     INTEGER PRIMARY KEY,
  name   TEXT NOT NULL UNIQUE,  -- canonical snake_case: 'character_histories'
  domain TEXT,                  -- same domain vocab as files.domain
  notes  TEXT                   -- free-text usage note
);


-- ── Aliases ───────────────────────────────────────────────────────────────────
-- Jordan-vocabulary → canonical concept.
-- "character generator stuff" → concept 'character_histories'

CREATE TABLE IF NOT EXISTS aliases (
  id         INTEGER PRIMARY KEY,
  concept_id INTEGER NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  alias      TEXT    NOT NULL,
  UNIQUE(alias COLLATE NOCASE)
);

CREATE INDEX IF NOT EXISTS idx_aliases_concept ON aliases(concept_id);


-- ── Concept ↔ File mapping ────────────────────────────────────────────────────
-- Many-to-many. A concept can span multiple files; a file can serve many concepts.

CREATE TABLE IF NOT EXISTS concept_files (
  concept_id INTEGER NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,
  path       TEXT    NOT NULL REFERENCES files(path)  ON DELETE CASCADE,
  PRIMARY KEY (concept_id, path)
);


-- ── Entities ──────────────────────────────────────────────────────────────────
-- Imported from references/proper_noun_registry.yaml.
-- Characters, territories, factions, organizations, etc.
-- Machine-managed by regenerator (mirrors the YAML).

CREATE TABLE IF NOT EXISTS entities (
  id        INTEGER PRIMARY KEY,
  key       TEXT NOT NULL UNIQUE,   -- yaml key: 'aldric_tormann'
  canonical TEXT NOT NULL,          -- display name: 'Aldric Tormann'
  category  TEXT,                   -- character | territory | faction | ...
  role      TEXT,
  location  TEXT,
  source    TEXT                    -- primary source file path
);

CREATE TABLE IF NOT EXISTS entity_aliases (
  id        INTEGER PRIMARY KEY,
  entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  alias     TEXT    NOT NULL,
  UNIQUE(alias COLLATE NOCASE)
);

CREATE INDEX IF NOT EXISTS idx_entity_aliases_entity ON entity_aliases(entity_id);


-- ── FTS5 — unified search across files + entities ────────────────────────────

CREATE VIRTUAL TABLE IF NOT EXISTS files_fts USING fts5(
  path      UNINDEXED,
  filename,
  headings,
  domain    UNINDEXED,
  content   = 'files',
  content_rowid = 'rowid'
);

-- Keep FTS5 in sync with files table
CREATE TRIGGER IF NOT EXISTS files_ai AFTER INSERT ON files BEGIN
  INSERT INTO files_fts(rowid, path, filename, headings, domain)
  VALUES (new.rowid, new.path, new.filename,
          COALESCE(new.headings,''), COALESCE(new.domain,''));
END;
CREATE TRIGGER IF NOT EXISTS files_au AFTER UPDATE ON files BEGIN
  INSERT INTO files_fts(files_fts, rowid, path, filename, headings, domain)
  VALUES ('delete', old.rowid, old.path, old.filename,
          COALESCE(old.headings,''), COALESCE(old.domain,''));
  INSERT INTO files_fts(rowid, path, filename, headings, domain)
  VALUES (new.rowid, new.path, new.filename,
          COALESCE(new.headings,''), COALESCE(new.domain,''));
END;
CREATE TRIGGER IF NOT EXISTS files_ad AFTER DELETE ON files BEGIN
  INSERT INTO files_fts(files_fts, rowid, path, filename, headings, domain)
  VALUES ('delete', old.rowid, old.path, old.filename,
          COALESCE(old.headings,''), COALESCE(old.domain,''));
END;


-- meta: 4 rows
INSERT OR REPLACE INTO meta (key, value) VALUES ('version', '1');
INSERT OR REPLACE INTO meta (key, value) VALUES ('generated', '2026-05-08T01:21:31Z');
INSERT OR REPLACE INTO meta (key, value) VALUES ('ttrpg_sha', '');
INSERT OR REPLACE INTO meta (key, value) VALUES ('file_count', '1259');

-- concepts: (empty — add curated entries here)
-- aliases: (empty — add curated entries here)
-- concept_files: (empty — add curated entries here)