"""
engine/tests/test_sigma_leverage_parity.py — parity + property tests for
engine.autoload.sigma_leverage.

TWO KINDS OF TEST LIVE HERE, AND THE DISTINCTION IS THE POINT:

1. PARITY against the two historical reference implementations, read from the golden
   table `engine/tests/goldens/sigma_leverage_parity.json` (1,758 rows). The table is
   generated by `tools/gen_sigma_parity_goldens.py`, which is the only thing that touches
   the oracles:
       tests/sim/v32-combat-balance/m1_dice_sigma_core.py  (numpy original, combat surface)
       audit/2026-06-03-contest-groundup/engine.py         (groundup engine, contest surface)

   This file used to import those two directly. That coupling failed in a way worth
   recording: the groundup load sat inside a bare `except` naming the pre-retirement
   `designs/audit/` path, so from 2026-07-19 (the designs/ retirement) to 2026-08-03 the
   reference read as absent and 184 parity cases SKIPPED while the suite reported green.
   The numpy arm had the same shape -- every m1 comparison was gated on `_numpy_available`,
   so a numpy-less environment silently tested nothing.

   Reading a committed table removes both failure modes: a missing table is an error, not
   a skip, and there is no numpy dependency left. It also lets engine/ travel on its own
   (fork plan of record §5: the fork carries engine/ and LEAVES audit/ and tests/).

2. PROPERTY / IDENTITY tests that need no oracle -- aliases, formula identities,
   saturation, monotonicity, floors, determinism. These assert things the reference
   implementations also satisfy but which are true of the port independently.

If the port's behaviour changes, (1) goes red. Regenerate the table ONLY when an oracle is
itself re-derived, and say why in the commit -- never to make a red test green.
"""
from __future__ import annotations

import json
import math
import os
import sys

import pytest

# ---------------------------------------------------------------------------
# Repo root on sys.path so `import engine.*` resolves when pytest runs anywhere.
# ---------------------------------------------------------------------------
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from engine.autoload import sigma_leverage as SL  # noqa: E402

# ---------------------------------------------------------------------------
# Golden table — the parity oracle, committed as data.
# ---------------------------------------------------------------------------
_GOLDENS = os.path.join(os.path.dirname(__file__), 'goldens', 'sigma_leverage_parity.json')

with open(_GOLDENS, encoding='utf-8') as _fh:      # deliberately unguarded: a missing
    _TABLE = json.load(_fh)                        # parity target is an error, not a skip
_ROWS = _TABLE["rows"]

# Input grids for the property tests below (the parity grids live in the generator).
NET_SIGMA_GRID = [-50.0, -5.0, -2.0, -1.5, -1.0, -0.5, 0.0,
                  0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 5.0, 10.0, 50.0]
POOL_GRID = [1, 5, 10, 26]
TN_GRID = [6, 7, 8]
TOL = 1e-9  # tight float tolerance (math vs numpy, same IEEE-754 doubles)


def _assert_close(got, want, label: str, tol: float = TOL):
    assert abs(got - want) <= tol, (
        f"{label}: got {got!r}, want {want!r}, delta={abs(got-want)!r}"
    )


# The table stores the ORACLE's positional order. VERIFIED 2026-08-03 by comparing
# inspect.signature across all nine functions: oracle, generator and port agree positionally on
# every one -- so these two branches are keyword-passing conveniences, NOT reorderings. An earlier
# version of this comment claimed "the port's argument order differs for two functions", which was
# false. It mattered enough to check: a symmetric mis-mapping (wrong in BOTH the generator and
# here) would produce a self-consistent table, pass all 1,758 rows, and still die to every mutant,
# because mutating the port breaks agreement regardless of whether the mapping is right.
def _call(fn: str, args: list):
    if fn == "net_boost":
        ns, pool, tn, capped = args
        return SL.net_boost(ns, pool, tn=tn, capped=capped)
    if fn == "p_success":
        base_ob, pool, ns, tn = args
        return SL.p_success(base_ob, pool, ns, tn)
    return getattr(SL, fn)(*args)


# ---------------------------------------------------------------------------
# (1) PARITY — every row of the golden table
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "row", _ROWS,
    ids=[f"{r['oracle']}:{r['fn']}:{','.join(str(a) for a in r['args'])}" for r in _ROWS])
def test_parity_against_golden_table(row):
    got = _call(row["fn"], row["args"])
    want = row["want"]
    if isinstance(want, float):
        _assert_close(got, want, f"{row['oracle']}.{row['fn']}({row['args']})")
    else:
        assert got == want, f"{row['oracle']}.{row['fn']}({row['args']}): got {got}, want {want}"


def test_golden_table_is_not_vacuous():
    """A table that loaded but is empty or one-sided would make every parity case pass.

    Floors are per-oracle and per-function so that losing one whole arm -- which is exactly
    what the bare-except and the numpy gate each did -- cannot hide behind the other's rows.
    """
    from collections import Counter
    by_oracle = Counter(r["oracle"] for r in _ROWS)
    assert by_oracle["m1"] >= 1400, by_oracle
    assert by_oracle["groundup"] >= 259, by_oracle
    fns = {r["fn"] for r in _ROWS}
    assert fns == {"sigma_n", "soft_cap", "sigma_space_ob_shift", "net_boost", "eff_ob",
                   "p_success", "levels_to_net_sigma", "level", "degree"}, sorted(fns)
    assert _TABLE["subject"] == "engine/autoload/sigma_leverage.py"


# ---------------------------------------------------------------------------
# (2) PROPERTIES — true of the port independently of any oracle
# ---------------------------------------------------------------------------

class TestSigmaN:
    """sigma_n(pool) — combat alias; sigma_N(pool) — contest alias."""

    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_sigma_N_alias(self, pool):
        assert SL.sigma_N(pool) == SL.sigma_n(pool), f"sigma_N != sigma_n at pool={pool}"

    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_sigma_n_formula(self, pool):
        """sigma_n = SIGMA_N_COEFF * sqrt(max(1, pool))."""
        expected = SL.SIGMA_N_COEFF * math.sqrt(max(1, pool))
        _assert_close(SL.sigma_n(pool), expected, f"sigma_n formula pool={pool}")

    def test_sigma_n_pool_floor(self):
        """Pool 0 and negative treated as pool=1."""
        assert SL.sigma_n(0) == SL.sigma_n(1)
        assert SL.sigma_n(-3) == SL.sigma_n(1)


class TestSoftCap:
    """soft_cap(net_sigma) — combat alias; eff_sigma(net_sigma) — contest alias."""

    @pytest.mark.parametrize("ns", NET_SIGMA_GRID)
    def test_eff_sigma_alias(self, ns):
        assert SL.eff_sigma(ns) == SL.soft_cap(ns), f"eff_sigma != soft_cap at net_sigma={ns}"

    @pytest.mark.parametrize("ns", NET_SIGMA_GRID)
    def test_soft_cap_formula(self, ns):
        """soft_cap = M_MAX * tanh(ns / M_MAX)."""
        expected = SL.M_MAX * math.tanh(ns / SL.M_MAX)
        _assert_close(SL.soft_cap(ns), expected, f"soft_cap formula ns={ns}")

    def test_saturation_positive(self):
        got = SL.soft_cap(SL.M_MAX * 100)
        assert abs(got - SL.M_MAX) < 1e-6, f"saturation failed: {got}"

    def test_saturation_negative(self):
        got = SL.soft_cap(-SL.M_MAX * 100)
        assert abs(got + SL.M_MAX) < 1e-6, f"floor saturation failed: {got}"

    def test_softcap_spec_checkpoints(self):
        """modifier_system_spec.md §3.1 spot-checks (2dp tolerance)."""
        for raw, want in [(0.5, 0.48), (1.0, 0.87), (2.0, 1.31), (3.0, 1.45)]:
            got = SL.soft_cap(raw)
            assert round(got, 2) == round(want, 2), (
                f"spec checkpoint raw={raw}: got {got:.3f}, want ~{want}"
            )

    def test_soft_cap_odd_zero(self):
        assert SL.soft_cap(0.0) == 0.0


class TestSigmaSpaceObShift:
    """Defined as net_sigma * sigma_n(pool); the sqrt(N) cancels in the z-score
    (the F1 uniform-modifier-impact property)."""

    @pytest.mark.parametrize("ns", NET_SIGMA_GRID)
    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_sigma_space_ob_shift_identity(self, ns, pool):
        """Exact, not approximate — same float ops, so a 1-ulp divergence is a real defect."""
        assert SL.sigma_space_ob_shift(ns, pool) == ns * SL.sigma_n(pool), (
            f"sigma_space_ob_shift != ns*sigma_n at ns={ns} pool={pool}"
        )


class TestNetBoost:

    @pytest.mark.parametrize("pool", POOL_GRID)
    @pytest.mark.parametrize("tn", TN_GRID)
    def test_net_boost_formula(self, pool, tn):
        """net_boost = eff_sigma(ns)*sigma_per_die[tn]*sqrt(pool) for a mid-range ns."""
        ns = 0.7
        _, sigma = SL.PER_DIE[tn]
        expected = SL.soft_cap(ns) * sigma * math.sqrt(max(1, pool))
        got = SL.net_boost(ns, pool, tn=tn, capped=True)
        _assert_close(got, expected, f"net_boost formula pool={pool} tn={tn}")

    def test_net_boost_zero_sigma(self):
        for pool in POOL_GRID:
            for tn in TN_GRID:
                assert SL.net_boost(0.0, pool, tn=tn) == 0.0

    def test_net_boost_tn7_equals_sigma_n(self):
        """At TN7, net_boost(ns, pool, capped=False) == ns*sigma_n(pool)
        because sigma_per_die[7]=0.800 == SIGMA_N_COEFF=0.8."""
        for ns in [0.5, 1.0, 2.0]:
            for pool in POOL_GRID:
                got = SL.net_boost(ns, pool, tn=7, capped=False)
                want = ns * SL.sigma_n(pool)
                _assert_close(got, want, f"TN7 net_boost == sigma_n*ns at ns={ns} pool={pool}")


class TestEffOb:

    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_eff_ob_floor(self, pool):
        """eff_ob never goes below OB_MIN=1 even at extreme positive net_sigma."""
        got = SL.eff_ob(1.0, pool, 100.0)
        assert got >= SL.OB_MIN, f"eff_ob below floor at pool={pool}: {got}"

    @pytest.mark.parametrize("ns", [-1.0, 0.0, 0.5, 1.5, 3.0])
    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_effective_ob_alias(self, ns, pool):
        """effective_ob(base_ob, net_dsigma, pool) == eff_ob(base_ob, pool, net_dsigma)."""
        base_ob = 3.0
        assert SL.effective_ob(base_ob, ns, pool) == SL.eff_ob(base_ob, pool, ns), (
            f"effective_ob != eff_ob at ns={ns} pool={pool}"
        )


class TestPSuccess:

    def test_p_success_range(self):
        for ns in NET_SIGMA_GRID:
            for pool in POOL_GRID:
                p = SL.p_success(4.0, pool, ns)
                assert 0.0 <= p <= 1.0, f"p_success out of [0,1]: {p}"

    def test_p_success_monotone_in_ns(self):
        pool, tn = 10, 7
        prev = SL.p_success(3.0, pool, -3.0, tn)
        for ns in [-2.0, -1.0, 0.0, 1.0, 2.0, 3.0]:
            curr = SL.p_success(3.0, pool, ns, tn)
            assert curr >= prev - 1e-12, f"p_success not monotone at ns={ns}"
            prev = curr

    def test_p_success_f1_uniformity(self):
        """F1 fix: +0.7sigma impact is uniform across pool sizes at 50% baseline.
        modifier_system_spec.md §2.1: +25.8pp at all pools (2dp)."""
        impacts = []
        for pool in [3, 5, 8, 12, 17, 20]:
            mu, _ = SL.PER_DIE[7]
            base_ob = mu * pool  # 50% baseline
            p0 = SL.p_success(base_ob, pool, 0.0, 7, capped=False)
            p1 = SL.p_success(base_ob, pool, 0.7, 7, capped=False)
            impacts.append(p1 - p0)
        spread = max(impacts) - min(impacts)
        avg = sum(impacts) / len(impacts)
        assert round(spread * 100, 1) == 0.0, f"F1 uniformity failed: spread={spread*100:.2f}pp"
        assert round(avg * 100, 1) == 25.8, f"F1 magnitude wrong: mean={avg*100:.1f}pp"


class TestLevel:
    """level(name) — contest-surface accessor. The groundup LEVEL dict is this module's
    LEVEL_SIGMA, so level(name) must equal LEVEL_SIGMA[name]."""

    EXPECTED = {"minor": 0.25, "moderate": 0.50, "strong": 0.75, "major": 1.00}

    @pytest.mark.parametrize("name,value", list(EXPECTED.items()))
    def test_level_matches_level_sigma(self, name, value):
        assert SL.level(name) == SL.LEVEL_SIGMA[name]
        assert SL.level(name) == value

    def test_level_covers_all_names(self):
        """Guards against LEVEL_SIGMA drifting out from under this accessor."""
        assert set(self.EXPECTED) == set(SL.LEVEL_SIGMA)
        for name in SL.LEVEL_SIGMA:
            assert SL.level(name) == SL.LEVEL_SIGMA[name]

    def test_level_unknown_raises(self):
        """Same contract as the dict lookup and the groundup engine."""
        with pytest.raises(KeyError):
            SL.level("catastrophic")


class TestLevelsToNetSigma:

    def test_neutral(self):
        assert SL.levels_to_net_sigma() == 0.0
        assert SL.levels_to_net_sigma(None, None) == 0.0

    def test_symmetric(self):
        assert SL.levels_to_net_sigma(["minor"], None) == -SL.levels_to_net_sigma(None, ["minor"])

    def test_additive(self):
        a = SL.levels_to_net_sigma(["minor", "moderate"])
        b = SL.LEVEL_SIGMA["minor"] + SL.LEVEL_SIGMA["moderate"]
        _assert_close(a, b, "levels additive")


class TestPoolAwareDegree:
    """degree(net, ob, pool) — pool-aware INTEGER bands (contest surface), distinct from
    dice_engine.degree_from_net. Cross-oracle parity is the golden table; these pin the named
    boundary cases.

    ⚠ The description "combat enum, 2*Ob bar" that stood here is STALE as of 2026-08-14: the owner
    no longer has a 2*Ob bar (Jordan's ruling replaced it with a margin ladder, ED-IN-0187). The
    contest surface is a declared HOLD against that ruling, so these cases still pass — but they
    pin the HELD behaviour, not canonical behaviour."""

    def test_bands_basic(self):
        assert (SL.degree(0, 3), SL.degree(3, 3), SL.degree(6, 3)) == (0, 2, 3)

    def test_failure_and_partial(self):
        assert SL.degree(0, 3) == 0
        assert SL.degree(-2, 3) == 0
        assert SL.degree(1, 3) == 1
        assert SL.degree(2, 3) == 1

    def test_legacy_pool_less_overwhelming(self):
        """pool=None → legacy 2*ob bar (net>=2*ob and net>=3)."""
        assert SL.degree(6, 3, None) == 3
        assert SL.degree(5, 3, None) == 2
        assert SL.degree(2, 1, None) == 2   # net<3 blocks legacy Overwhelming


class TestRollNet:
    """Structural — dice_engine delegation."""

    def test_returns_int(self):
        import random as _random
        assert isinstance(SL.roll_net(5, rng=_random.Random(42)), int)

    def test_pool_floor(self):
        """Pool <= 0 is treated as pool=1 (no crash)."""
        import random as _random
        assert isinstance(SL.roll_net(0, rng=_random.Random(0)), int)

    def test_seeded_deterministic(self):
        import random as _random
        assert SL.roll_net(10, rng=_random.Random(7)) == SL.roll_net(10, rng=_random.Random(7))


class TestRollNetContinuous:
    """Structural — dice_engine delegation."""

    def test_returns_float(self):
        import random as _random
        assert isinstance(SL.roll_net_continuous(5, rng=_random.Random(99)), float)

    def test_seeded_deterministic(self):
        import random as _random
        assert (SL.roll_net_continuous(10, rng=_random.Random(13))
                == SL.roll_net_continuous(10, rng=_random.Random(13)))
