"""
engine/tests/test_sigma_leverage_parity.py — parity + property tests for
engine.autoload.sigma_leverage.

TWO KINDS OF TEST LIVE HERE, AND THE DISTINCTION IS THE POINT:

1. PARITY against the two historical reference implementations, read from the golden
   table `engine/tests/goldens/sigma_leverage_parity.json` (1,758 rows). The table is
   generated by `tools/gen_sigma_parity_goldens.py`, which is the only thing that touches
   the oracles:
       tests/sim/v32-combat-balance/m1_dice_sigma_core.py  (numpy original, combat surface)
       audit/2026-06-03-contest-groundup/engine.py         (groundup engine, contest surface)

   This file used to import those two directly. That coupling failed in a way worth
   recording: the groundup load sat inside a bare `except` naming the pre-retirement
   `designs/audit/` path, so from 2026-07-19 (the designs/ retirement) to 2026-08-03 the
   reference read as absent and 184 parity cases SKIPPED while the suite reported green.
   The numpy arm had the same shape -- every m1 comparison was gated on `_numpy_available`,
   so a numpy-less environment silently tested nothing.

   Reading a committed table removes both failure modes: a missing table is an error, not
   a skip, and there is no numpy dependency left. It also lets engine/ travel on its own
   (fork plan of record §5: the fork carries engine/ and LEAVES audit/ and tests/).

2. PROPERTY / IDENTITY tests that need no oracle -- aliases, formula identities,
   saturation, monotonicity, floors, determinism. These assert things the reference
   implementations also satisfy but which are true of the port independently.

If the port's behaviour changes, (1) goes red. Regenerate the table ONLY when an oracle is
itself re-derived, and say why in the commit -- never to make a red test green.
"""
from __future__ import annotations

import json
import math
import os
import sys

import pytest

# ---------------------------------------------------------------------------
# Repo root on sys.path so `import engine.*` resolves when pytest runs anywhere.
# ---------------------------------------------------------------------------
_REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from engine.autoload import sigma_leverage as SL  # noqa: E402
# ED-SC-0032: `degree` and the de-saturation bar MOVED out of the engine into the subsystem
# that owns them. This file still tests the sigma layer; the degree half now addresses the
# contest package, and that relocation is itself the point of the ruling being executed.
from systems.social_contest.sim.contest import degree_extension as CD  # noqa: E402

# ---------------------------------------------------------------------------
# Golden table — the parity oracle, committed as data.
# ---------------------------------------------------------------------------
_GOLDENS = os.path.join(os.path.dirname(__file__), 'goldens', 'sigma_leverage_parity.json')

with open(_GOLDENS, encoding='utf-8') as _fh:      # deliberately unguarded: a missing
    _TABLE = json.load(_fh)                        # parity target is an error, not a skip
_ROWS = _TABLE["rows"]

# ---------------------------------------------------------------------------
# TN7-ONLY PARTITION (ED-IN-0196)
# [Jordan, 2026-08-25: "TN7 always. Never change TN anywhere ever."]
#
# The golden table was generated when canon carried a three-value TN scale, so 768 of its
# 1,758 rows exercise TN 6 (384) and TN 8 (384). Those TNs no longer exist: sigma_leverage's
# PER_DIE now holds only the TN 7 row, so calling net_boost/p_success at 6 or 8 raises
# KeyError by design.
#
# THE TABLE IS NOT REGENERATED. This file's own header forbids regenerating it to make a red
# test green, and that rule is respected: the oracles were not re-derived and the committed
# rows are untouched historical record. What changed is the CLAIM — parity is asserted on the
# TN that exists, and the superseded rows are re-purposed below into a positive assertion
# that non-7 TN is now refused. Coverage is not silently dropped; it is inverted.
_TN_ARG_INDEX = {"net_boost": 2, "p_success": 3}   # positional TN, per _call's unpacking


def _row_tn(row):
    """The TN a row exercises, or None for the TN-independent functions."""
    i = _TN_ARG_INDEX.get(row["fn"])
    return row["args"][i] if i is not None and len(row["args"]) > i else None


_LIVE_ROWS = [r for r in _ROWS if _row_tn(r) in (None, 7)]
_SUPERSEDED_TN_ROWS = [r for r in _ROWS if _row_tn(r) not in (None, 7)]

# ---------------------------------------------------------------------------
# PRE-RULING-LADDER PARTITION (ED-SC-0031)
#
# The table's 255 `degree` rows were generated from the groundup oracle's own private ladder,
# which `sigma_leverage.degree` re-implemented. That ladder was retired 2026-08-27: the bands
# are now `dice_engine.degree_from_net`'s (Jordan's 2026-08-14 ruling), with one declared
# extension that may only demote Overwhelming to Success.
#
# 47 of the 255 rows record cells the ruling MOVED; the other 208 still agree. Splitting the
# rows by whether they happen to agree would be exactly the WRONG partition — it keeps a subset
# chosen BY the current implementation's answers, which is a table that agrees with the code by
# construction and proves nothing. So the whole function leaves the parity arm, on the honest
# ground that the oracle behind those rows is superseded, and its coverage is replaced by
# `TestPoolAwareDegree::test_bands_are_the_owners`, which checks ~4,900 cells against the owner
# rather than 255 against a retired oracle.
#
# THE TABLE IS NOT REGENERATED — same rule as the TN partition above. The rows stay as committed
# historical record, and the inversion below turns them into a positive assertion.
_LIVE_ROWS = [r for r in _LIVE_ROWS if r["fn"] != "degree"]
_PRE_RULING_DEGREE_ROWS = [r for r in _ROWS if r["fn"] == "degree"]

# Input grids for the property tests below (the parity grids live in the generator).
NET_SIGMA_GRID = [-50.0, -5.0, -2.0, -1.5, -1.0, -0.5, 0.0,
                  0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 5.0, 10.0, 50.0]
POOL_GRID = [1, 5, 10, 26]
TN_GRID = [7]        # TN7 always (ED-IN-0196); 6 and 8 are superseded canon
TOL = 1e-9  # tight float tolerance (math vs numpy, same IEEE-754 doubles)


def _assert_close(got, want, label: str, tol: float = TOL):
    assert abs(got - want) <= tol, (
        f"{label}: got {got!r}, want {want!r}, delta={abs(got-want)!r}"
    )


# The table stores the ORACLE's positional order. VERIFIED 2026-08-03 by comparing
# inspect.signature across all nine functions: oracle, generator and port agree positionally on
# every one -- so these two branches are keyword-passing conveniences, NOT reorderings. An earlier
# version of this comment claimed "the port's argument order differs for two functions", which was
# false. It mattered enough to check: a symmetric mis-mapping (wrong in BOTH the generator and
# here) would produce a self-consistent table, pass all 1,758 rows, and still die to every mutant,
# because mutating the port breaks agreement regardless of whether the mapping is right.
def _call(fn: str, args: list):
    if fn == "net_boost":
        ns, pool, tn, capped = args
        return SL.net_boost(ns, pool, tn=tn, capped=capped)
    if fn == "p_success":
        base_ob, pool, ns, tn = args
        return SL.p_success(base_ob, pool, ns, tn)
    return getattr(SL, fn)(*args)


# ---------------------------------------------------------------------------
# (1) PARITY — every row of the golden table
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(
    "row", _LIVE_ROWS,
    ids=[f"{r['oracle']}:{r['fn']}:{','.join(str(a) for a in r['args'])}" for r in _LIVE_ROWS])
def test_parity_against_golden_table(row):
    got = _call(row["fn"], row["args"])
    want = row["want"]
    if isinstance(want, float):
        _assert_close(got, want, f"{row['oracle']}.{row['fn']}({row['args']})")
    else:
        assert got == want, f"{row['oracle']}.{row['fn']}({row['args']}): got {got}, want {want}"


def test_golden_table_is_not_vacuous():
    """A table that loaded but is empty or one-sided would make every parity case pass.

    Floors are per-oracle and per-function so that losing one whole arm -- which is exactly
    what the bare-except and the numpy gate each did -- cannot hide behind the other's rows.
    """
    from collections import Counter
    by_oracle = Counter(r["oracle"] for r in _LIVE_ROWS)
    # m1's floor dropped 1400 -> 731 when the TN 6/8 rows left the live set (ED-IN-0196).
    # groundup dropped 259 -> 4 when the 255 `degree` rows left it (ED-SC-0031). Stated rather
    # than quietly lowered: that arm is now four `level` rows plus inverted coverage. The
    # replacement for the 255 is TestPoolAwareDegree::test_bands_are_the_owners — a stronger
    # claim over a wider domain — but it lives in this file, not in the table, so this floor
    # must not pretend the table still carries them.
    assert by_oracle["m1"] >= 731, by_oracle
    assert by_oracle["groundup"] >= 4, by_oracle
    assert len(_PRE_RULING_DEGREE_ROWS) == 255, len(_PRE_RULING_DEGREE_ROWS)
    fns = {r["fn"] for r in _LIVE_ROWS}
    assert fns == {"sigma_n", "soft_cap", "sigma_space_ob_shift", "net_boost", "eff_ob",
                   "p_success", "levels_to_net_sigma", "level"}, sorted(fns)
    assert _TABLE["subject"] == "engine/autoload/sigma_leverage.py"


def test_the_superseded_rows_are_exactly_the_non_7_TN_ones():
    """The partition removed dead canon and nothing else (§0.1 point 2: assert it asserted).

    A silent widening of this filter would quietly delete live parity coverage, so the
    counts and the TN values are both pinned.
    """
    assert len(_LIVE_ROWS) + len(_SUPERSEDED_TN_ROWS) + len(_PRE_RULING_DEGREE_ROWS) == len(_ROWS)
    assert len(_SUPERSEDED_TN_ROWS) == 768, len(_SUPERSEDED_TN_ROWS)
    assert {_row_tn(r) for r in _SUPERSEDED_TN_ROWS} == {6, 8}
    assert all(_row_tn(r) in (None, 7) for r in _LIVE_ROWS)
    # The two partitions must not overlap, or the sum above balances by double-counting.
    assert not [r for r in _PRE_RULING_DEGREE_ROWS if _row_tn(r) not in (None, 7)]
    assert not [r for r in _LIVE_ROWS if r["fn"] == "degree"]


@pytest.mark.parametrize("tn", [6, 8])
def test_a_superseded_TN_is_refused_not_silently_answered(tn):
    """The inversion. These TNs used to have 384 parity rows each; now they must RAISE.

    This is the point of the ruling in this module: a stray non-7 TN fails loudly instead of
    resolving against a dead EV row. If sigma_leverage ever answers at TN 6 or 8 again,
    someone has restored the superseded scale and this fails.
    """
    row = next(r for r in _SUPERSEDED_TN_ROWS if _row_tn(r) == tn)
    with pytest.raises(KeyError):
        _call(row["fn"], row["args"])


def test_the_superseded_degree_rows_are_the_pre_ruling_ladder():
    """The degree inversion. These 255 rows are not deleted — they are re-read as history.

    The claim asserted here is what the partition above says out loud: the rows record the
    PRE-RULING ladder, so a specific, enumerated subset of them must now DISAGREE with the port,
    and the rest must still agree because the two ladders genuinely coincide there. Pinning the
    disagreement count is what makes this an assertion rather than a shrug: if a future change
    re-broadens `sigma_leverage.degree` back toward the old private bands, the count falls and
    this fails, which a deletion of the rows could never catch.

    The 47 moved cells are the ruling's own three boundary changes: `net == ob` Success -> Partial,
    `0 < net < ob` Partial -> Failure, and the retired pool-less `net >= 2*ob` Overwhelming bar.
    """
    moved = [r for r in _PRE_RULING_DEGREE_ROWS if CD.degree(*r["args"]) != r["want"]]
    kept = [r for r in _PRE_RULING_DEGREE_ROWS if CD.degree(*r["args"]) == r["want"]]

    # ⚠ THE SET, NOT THE COUNT. An earlier draft asserted `len(moved) == 47`, which is invariant
    # under any change that makes one kept row disagree while making one moved row agree — the
    # rows it replaced were POINTWISE, so a cardinality pin was strictly weaker on exactly the
    # domain it was standing in for. The `ob` here is `args[1]`, and the three obs the generator
    # sweeps land 9 / 15 / 23 disagreements respectively.
    by_ob = {}
    for r in moved:
        by_ob[r["args"][1]] = by_ob.get(r["args"][1], 0) + 1
    assert by_ob == {1.0: 9, 2.0: 15, 3.0: 23}, (
        f"the pre-ruling disagreements are distributed as {by_ob}, expected "
        "{1.0: 9, 2.0: 15, 3.0: 23} — the ladder has moved since ED-SC-0031 and this disposition "
        "needs re-deriving, not re-pinning"
    )
    assert len(moved) == 47 and len(kept) == 208
    # Every disagreement must be on a row the ruling's three boundary changes account for, i.e.
    # the pre-ruling answer is one the new ladder cannot produce for that (net, ob).
    for r in moved:
        net, ob = r["args"][0], r["args"][1]
        assert net > 0 and net < ob + 3, (
            f"degree{tuple(r['args'])} disagrees but is outside the bands the ruling moved "
            "(0 < net < ob+3) — this is a disagreement the disposition does not explain"
        )
    # Every moved row must move in a direction the ruling accounts for: the old ladder was more
    # generous at every one of its three changed boundaries, so no cell may band HIGHER now.
    for r in moved:
        assert CD.degree(*r["args"]) < r["want"], (
            f"degree{tuple(r['args'])} banded UP ({r['want']} -> {CD.degree(*r['args'])}); the "
            "2026-08-14 ruling only ever tightened this surface"
        )


# ---------------------------------------------------------------------------
# (2) PROPERTIES — true of the port independently of any oracle
# ---------------------------------------------------------------------------

class TestSigmaN:
    """sigma_n(pool) — combat alias; sigma_N(pool) — contest alias."""

    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_sigma_N_alias(self, pool):
        assert SL.sigma_N(pool) == SL.sigma_n(pool), f"sigma_N != sigma_n at pool={pool}"

    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_sigma_n_formula(self, pool):
        """sigma_n = SIGMA_N_COEFF * sqrt(max(1, pool))."""
        expected = SL.SIGMA_N_COEFF * math.sqrt(max(1, pool))
        _assert_close(SL.sigma_n(pool), expected, f"sigma_n formula pool={pool}")

    def test_sigma_n_pool_floor(self):
        """Pool 0 and negative treated as pool=1."""
        assert SL.sigma_n(0) == SL.sigma_n(1)
        assert SL.sigma_n(-3) == SL.sigma_n(1)


class TestSoftCap:
    """soft_cap(net_sigma) — combat alias; eff_sigma(net_sigma) — contest alias."""

    @pytest.mark.parametrize("ns", NET_SIGMA_GRID)
    def test_eff_sigma_alias(self, ns):
        assert SL.eff_sigma(ns) == SL.soft_cap(ns), f"eff_sigma != soft_cap at net_sigma={ns}"

    @pytest.mark.parametrize("ns", NET_SIGMA_GRID)
    def test_soft_cap_formula(self, ns):
        """soft_cap = M_MAX * tanh(ns / M_MAX)."""
        expected = SL.M_MAX * math.tanh(ns / SL.M_MAX)
        _assert_close(SL.soft_cap(ns), expected, f"soft_cap formula ns={ns}")

    def test_saturation_positive(self):
        got = SL.soft_cap(SL.M_MAX * 100)
        assert abs(got - SL.M_MAX) < 1e-6, f"saturation failed: {got}"

    def test_saturation_negative(self):
        got = SL.soft_cap(-SL.M_MAX * 100)
        assert abs(got + SL.M_MAX) < 1e-6, f"floor saturation failed: {got}"

    def test_softcap_spec_checkpoints(self):
        """modifier_system_spec.md §3.1 spot-checks (2dp tolerance)."""
        for raw, want in [(0.5, 0.48), (1.0, 0.87), (2.0, 1.31), (3.0, 1.45)]:
            got = SL.soft_cap(raw)
            assert round(got, 2) == round(want, 2), (
                f"spec checkpoint raw={raw}: got {got:.3f}, want ~{want}"
            )

    def test_soft_cap_odd_zero(self):
        assert SL.soft_cap(0.0) == 0.0


class TestSigmaSpaceObShift:
    """Defined as net_sigma * sigma_n(pool); the sqrt(N) cancels in the z-score
    (the F1 uniform-modifier-impact property)."""

    @pytest.mark.parametrize("ns", NET_SIGMA_GRID)
    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_sigma_space_ob_shift_identity(self, ns, pool):
        """Exact, not approximate — same float ops, so a 1-ulp divergence is a real defect."""
        assert SL.sigma_space_ob_shift(ns, pool) == ns * SL.sigma_n(pool), (
            f"sigma_space_ob_shift != ns*sigma_n at ns={ns} pool={pool}"
        )


class TestNetBoost:

    @pytest.mark.parametrize("pool", POOL_GRID)
    @pytest.mark.parametrize("tn", TN_GRID)
    def test_net_boost_formula(self, pool, tn):
        """net_boost = eff_sigma(ns)*sigma_per_die[tn]*sqrt(pool) for a mid-range ns."""
        ns = 0.7
        _, sigma = SL.PER_DIE[tn]
        expected = SL.soft_cap(ns) * sigma * math.sqrt(max(1, pool))
        got = SL.net_boost(ns, pool, tn=tn, capped=True)
        _assert_close(got, expected, f"net_boost formula pool={pool} tn={tn}")

    def test_net_boost_zero_sigma(self):
        for pool in POOL_GRID:
            for tn in TN_GRID:
                assert SL.net_boost(0.0, pool, tn=tn) == 0.0

    def test_net_boost_tn7_equals_sigma_n(self):
        """At TN7, net_boost(ns, pool, capped=False) == ns*sigma_n(pool)
        because sigma_per_die[7]=0.800 == SIGMA_N_COEFF=0.8."""
        for ns in [0.5, 1.0, 2.0]:
            for pool in POOL_GRID:
                got = SL.net_boost(ns, pool, tn=7, capped=False)
                want = ns * SL.sigma_n(pool)
                _assert_close(got, want, f"TN7 net_boost == sigma_n*ns at ns={ns} pool={pool}")


class TestEffOb:

    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_eff_ob_floor(self, pool):
        """eff_ob never goes below OB_MIN=1 even at extreme positive net_sigma."""
        got = SL.eff_ob(1.0, pool, 100.0)
        assert got >= SL.OB_MIN, f"eff_ob below floor at pool={pool}: {got}"

    @pytest.mark.parametrize("ns", [-1.0, 0.0, 0.5, 1.5, 3.0])
    @pytest.mark.parametrize("pool", POOL_GRID)
    def test_effective_ob_alias(self, ns, pool):
        """effective_ob(base_ob, net_dsigma, pool) == eff_ob(base_ob, pool, net_dsigma)."""
        base_ob = 3.0
        assert SL.effective_ob(base_ob, ns, pool) == SL.eff_ob(base_ob, pool, ns), (
            f"effective_ob != eff_ob at ns={ns} pool={pool}"
        )


class TestPSuccess:

    def test_p_success_range(self):
        for ns in NET_SIGMA_GRID:
            for pool in POOL_GRID:
                p = SL.p_success(4.0, pool, ns)
                assert 0.0 <= p <= 1.0, f"p_success out of [0,1]: {p}"

    def test_p_success_monotone_in_ns(self):
        pool, tn = 10, 7
        prev = SL.p_success(3.0, pool, -3.0, tn)
        for ns in [-2.0, -1.0, 0.0, 1.0, 2.0, 3.0]:
            curr = SL.p_success(3.0, pool, ns, tn)
            assert curr >= prev - 1e-12, f"p_success not monotone at ns={ns}"
            prev = curr

    def test_p_success_f1_uniformity(self):
        """F1 fix: +0.7sigma impact is uniform across pool sizes at 50% baseline.
        modifier_system_spec.md §2.1: +25.8pp at all pools (2dp)."""
        impacts = []
        for pool in [3, 5, 8, 12, 17, 20]:
            mu, _ = SL.PER_DIE[7]
            base_ob = mu * pool  # 50% baseline
            p0 = SL.p_success(base_ob, pool, 0.0, 7, capped=False)
            p1 = SL.p_success(base_ob, pool, 0.7, 7, capped=False)
            impacts.append(p1 - p0)
        spread = max(impacts) - min(impacts)
        avg = sum(impacts) / len(impacts)
        assert round(spread * 100, 1) == 0.0, f"F1 uniformity failed: spread={spread*100:.2f}pp"
        assert round(avg * 100, 1) == 25.8, f"F1 magnitude wrong: mean={avg*100:.1f}pp"


class TestLevel:
    """level(name) — contest-surface accessor. The groundup LEVEL dict is this module's
    LEVEL_SIGMA, so level(name) must equal LEVEL_SIGMA[name]."""

    EXPECTED = {"minor": 0.25, "moderate": 0.50, "strong": 0.75, "major": 1.00}

    @pytest.mark.parametrize("name,value", list(EXPECTED.items()))
    def test_level_matches_level_sigma(self, name, value):
        assert SL.level(name) == SL.LEVEL_SIGMA[name]
        assert SL.level(name) == value

    def test_level_covers_all_names(self):
        """Guards against LEVEL_SIGMA drifting out from under this accessor."""
        assert set(self.EXPECTED) == set(SL.LEVEL_SIGMA)
        for name in SL.LEVEL_SIGMA:
            assert SL.level(name) == SL.LEVEL_SIGMA[name]

    def test_level_unknown_raises(self):
        """Same contract as the dict lookup and the groundup engine."""
        with pytest.raises(KeyError):
            SL.level("catastrophic")


class TestLevelsToNetSigma:

    def test_neutral(self):
        assert SL.levels_to_net_sigma() == 0.0
        assert SL.levels_to_net_sigma(None, None) == 0.0

    def test_symmetric(self):
        assert SL.levels_to_net_sigma(["minor"], None) == -SL.levels_to_net_sigma(None, ["minor"])

    def test_additive(self):
        a = SL.levels_to_net_sigma(["minor", "moderate"])
        b = SL.LEVEL_SIGMA["minor"] + SL.LEVEL_SIGMA["moderate"]
        _assert_close(a, b, "levels additive")


class TestPoolAwareDegree:
    """degree(net, ob, pool) — the OWNER'S ladder as an ordinal, plus one declared extension.

    MIGRATED 2026-08-27 (ED-SC-0031). This class used to pin the contest surface's own private
    bands, held against Jordan's 2026-08-14 ladder ruling. The hold is over: the bands are
    `dice_engine.degree_from_net`'s, and the only contest-specific behaviour left is a
    de-saturation bar that can DEMOTE Overwhelming to Success and do nothing else.

    So these tests now do two different jobs and both are needed. `test_bands_are_the_owners`
    proves there is no local re-banding at all — over a domain, not at three named points, since
    three points is exactly what let the old private ladder look equivalent. The extension tests
    then pin the one thing that IS local.
    """

    def test_bands_are_the_owners(self):
        """No local re-banding anywhere on the pool-less domain, integer AND fractional.

        Point-wise equality with `degree_from_net` over the whole domain is the assertion that
        cannot be satisfied by a second ladder that happens to agree at the named cells — which
        is how `sigma_leverage.degree` escaped the 2026-08-12 degree-vocabulary census.
        """
        from engine.autoload import dice_engine as DE
        checked = 0
        for ob10 in range(0, 61):          # ob 0.0 .. 6.0 in tenths
            ob = ob10 / 10.0
            for net4 in range(-20, 61):    # net -5.0 .. 15.0 in quarters
                net = net4 / 4.0
                assert CD.degree(net, ob) == DE.DEGREE_ORDINAL[DE.degree_from_net(net, ob)], (
                    f"sigma_leverage.degree({net}, {ob}) disagrees with the owner"
                )
                checked += 1
        assert checked >= 4000, f"only {checked} cells checked — the domain loop is broken"

    def test_the_named_ruling_cells(self):
        """The three cells the 2026-08-14 ruling moved, pinned by value so the flip is explicit."""
        assert CD.degree(3, 3) == 1      # margin 0 — met, not exceeded -> Partial (was 2)
        assert CD.degree(2, 3) == 0      # margin -1 -> Failure (was 1, the old `net < ob` Partial)
        assert CD.degree(6, 3) == 3      # margin 3 -> Overwhelming (unchanged)
        assert CD.degree(0, 3) == 0
        assert CD.degree(-2, 3) == 0

    def test_the_extension_only_ever_demotes_the_top_band(self):
        """The contest extension's declared contract, asserted as a property over the domain.

        It may turn Overwhelming into Success. It may not promote, and it may not touch Failure,
        Partial, or Success. An extension that could move a lower boundary would be the old
        private ladder under a new name, so this is the assertion that keeps the migration real.
        """
        moved = 0
        for pool in (1, 2, 4, 8, 12, 20, 30):
            for net4 in range(-20, 81):
                net = net4 / 4.0
                base = CD.degree(net, 2.0)
                ext = CD.degree(net, 2.0, pool)
                if ext != base:
                    assert base == 3 and ext == 2, (
                        f"pool={pool} net={net}: extension moved {base} -> {ext}; it may only "
                        "demote Overwhelming to Success"
                    )
                    moved += 1
        assert moved > 0, "the extension never fired — this property test is vacuous"

    def test_the_extension_de_saturates(self):
        """WHY the extension exists: without it the top band saturates as pools grow.

        Measured against the ACTUAL net distribution — N(mu*pool, sigma*sqrt(pool)), the
        continuous engine's own model — not against a share of the net axis. The axis-share
        reading is the wrong one and was tried first: it says the owner bands 92% of the range
        Overwhelming at pool 30 while the true rate is 95%.

        ⚠ THE FLATNESS ASSERTION AN EARLIER DRAFT PUT HERE WAS AN ALGEBRAIC IDENTITY AND COULD
        NOT FAIL. Where the extension binds, `bar - mean == OVERWHELM_SIGMA*SD_PER_DIE*sqrt(pool)`
        and `sd == SD_PER_DIE*sqrt(pool)`, so `z` is IDENTICALLY `OVERWHELM_SIGMA` and the rate is
        `1 - Phi(0.85)` at every binding pool. Asserting those six identical floats span < 0.05
        is `0.0 < 0.05`. That identity is the extension's actual design property, so it is
        asserted AS an identity below — deliberately, where it can at least catch the bar losing
        its sqrt(pool) scaling — and the falsifiable claims are stated separately.
        """
        def p_overwhelming(pool, ob, with_ext):
            mean = SL.MU_PER_DIE * pool
            sd = SL.SD_PER_DIE * math.sqrt(pool)
            bar = ob + CD.owner_overwhelming_margin()   # the OWNER's bar, read off the owner
            if with_ext:
                bar = max(bar, CD.overwhelm_bar(pool))
            return 1.0 - SL._phi((bar - mean) / sd)

        # (1) FALSIFIABLE: the saturation the extension exists to prevent.
        assert p_overwhelming(30, 2.0, with_ext=False) > 0.9, (
            "precondition failed: the owner's ladder is supposed to saturate at high pool, and "
            "if it no longer does then the extension has lost its reason to exist"
        )
        assert p_overwhelming(30, 2.0, with_ext=True) < 0.25

        # (2) THE IDENTITY, asserted as one. It fails if the bar stops scaling as mu*pool +
        # k*sigma*sqrt(pool) — e.g. a fixed offset, or sqrt dropped — which is the real way this
        # property breaks, and which the six-float spread check could never see.
        expected = 1.0 - SL._phi(CD.OVERWHELM_SIGMA)
        for pool in (8, 12, 16, 20, 25, 30):
            assert abs(p_overwhelming(pool, 2.0, with_ext=True) - expected) < 1e-12, (
                f"pool {pool}: the extension's rate is not 1-Phi(OVERWHELM_SIGMA); the bar has "
                "stopped tracking the pool's own mean and sigma"
            )

        # (3) FALSIFIABLE, and the claim an earlier draft got wrong: where it is inert depends on
        # `ob`. "Pool 8" was a measurement of resolver.py's default obstacle, not a contract.
        assert [CD.crossover_pool(ob) for ob in (1.0, 2.0, 3.0)] == [6, 8, 10]
        for ob in (1.0, 2.0, 3.0):
            x = CD.crossover_pool(ob)
            for pool in range(1, x):
                assert p_overwhelming(pool, ob, True) == p_overwhelming(pool, ob, False), (
                    f"ob {ob}, pool {pool}: below its crossover the extension must be inert"
                )
            assert p_overwhelming(x, ob, True) < p_overwhelming(x, ob, False), (
                f"ob {ob}: the extension does nothing at its own crossover pool {x}"
            )

    def test_the_extension_is_the_owner_at_every_band_but_the_top_pool_aware_too(self):
        """The pool-AWARE domain, checked against the owner rather than against a retired oracle.

        ⚠ THIS TEST EXISTS BECAUSE THE PARTITION ABOVE LOST COVERAGE THE FIRST WRITE-UP CLAIMED
        IT HAD REPLACED. Of the 255 removed `degree` rows, 225 are pool-AWARE; the
        `test_bands_are_the_owners` sweep passes no third argument and replaces only the 30
        pool-less ones. Saying the removal was "replaced by ~4,900 cells" compared two different
        domains. This is the pool-aware half: every cell must be the owner's band, EXCEPT where
        the declared extension demotes 3 to 2, and that exception must itself be exactly
        `net < overwhelm_bar(pool)`.
        """
        from engine.autoload import dice_engine as DE
        demoted = checked = 0
        for pool in (1, 2, 5, 9, 16, 22, 25, 30):
            for ob10 in range(0, 41, 5):
                ob = ob10 / 10.0
                for net4 in range(-20, 4 * (2 * max(pool, 3)) + 1):
                    net = net4 / 4.0
                    owner = DE.DEGREE_ORDINAL[DE.degree_from_net(net, ob)]
                    got = CD.degree(net, ob, pool)
                    checked += 1
                    if got == owner:
                        continue
                    demoted += 1
                    assert (owner, got) == (3, 2), (
                        f"pool={pool} ob={ob} net={net}: {owner} -> {got}, only 3 -> 2 is legal"
                    )
                    assert net < CD.overwhelm_bar(pool), (
                        f"pool={pool} ob={ob} net={net} was demoted while clearing the bar"
                    )
        assert checked >= 9_000, f"only {checked} pool-aware cells checked"
        assert demoted >= 100, (
            f"only {demoted} cells demoted across the sweep — the extension is barely reachable "
            "on this domain and the test is close to vacuous"
        )


class TestRollNet:
    """Structural — dice_engine delegation."""

    def test_returns_int(self):
        import random as _random
        assert isinstance(SL.roll_net(5, rng=_random.Random(42)), int)

    def test_pool_floor(self):
        """Pool <= 0 is treated as pool=1 (no crash)."""
        import random as _random
        assert isinstance(SL.roll_net(0, rng=_random.Random(0)), int)

    def test_seeded_deterministic(self):
        import random as _random
        assert SL.roll_net(10, rng=_random.Random(7)) == SL.roll_net(10, rng=_random.Random(7))


class TestRollNetContinuous:
    """Structural — dice_engine delegation."""

    def test_returns_float(self):
        import random as _random
        assert isinstance(SL.roll_net_continuous(5, rng=_random.Random(99)), float)

    def test_seeded_deterministic(self):
        import random as _random
        assert (SL.roll_net_continuous(10, rng=_random.Random(13))
                == SL.roll_net_continuous(10, rng=_random.Random(13)))
