import yaml

def SR(need, why, hardness):
    return {"need": need, "why": why, "hardness": hardness}

cases = []

# ---------------- NPC-088 Carin Vedel ----------------
cases.append({
    "id": "NPC-088",
    "name": "Carin Vedel",
    "one_line": "A copyist with no institutional position who hand-reproduces suppressed Einhir cultural texts -- the lowest-agency case in the roster.",
    "scale": "person",
    "season_requires": [
        SR("A person holding no office, post, or command must be able to perform a repeated, multi-week task (copying a text) that the engine tracks as ongoing work-in-progress with a start and an end, not only as a single instantaneous action.",
           "Without this, her entire vocation -- the only thing she does -- cannot exist as a mechanical activity; she has nothing else to be tracked doing across a season.",
           "core"),
        SR("The physical product of her labor (a copied text) must be able to exist as a persistent object that can be found, carried, hidden, given away, or destroyed independently of her.",
           "Without an object that outlives the scene in which it was made, being a 'propagation mechanism' is a label with nothing underneath it -- no copy to seize, gift, or discover later.",
           "core"),
        SR("Simply possessing the product of her labor must be able to trigger consequences for whoever holds it, independent of whether the act of copying was ever observed.",
           "Her arc_trajectory states 'possession is a heresy charge'; if the engine only fires consequences on observed actions and not on a discoverable possessed-object state, this defining risk of her existence has nothing to attach to.",
           "core"),
        SR("Her work must be able to accumulate institutional attention gradually across multiple undiscovered seasons, not only through a single detected incident.",
           "Her arc_trajectory states her copies 'increase Church AP' -- a slow accumulation effect. If the only exposure channel is per-incident detection, the specific ongoing trickle of risk she represents has nothing to attach to.",
           "important"),
        SR("A person with no faction rank, no assigned Duty, and no tracked Standing must still be able to generate a scene opportunity that brings a player into contact with her.",
           "The engine's own scene-generation surfaces named NPCs chiefly through Duty-alignment, Conviction name-matching, or Outreach gated on Disposition >= +2 and a fired faction priority-tree action -- none of which a person with no office and no faction priority tree can satisfy on her own. Without another channel she is invisible to play by construction.",
           "core"),
        SR("UNCLEAR: whether the texts she copies are ordinary suppressed-but-mundane cultural material or Thread-substrate content of the kind described elsewhere as legible only above a Thread Sensitivity threshold -- the source never states which, and a non-sensitive copyist's ability to faithfully reproduce either category is not the same.",
           "If her material is the Thread-substrate kind, a non-sensitive copyist cannot actually preserve its real content, which undercuts the premise that her hand-copying preserves anything true; if it is mundane cultural material, no such limit applies. The source does not resolve this.",
           "important"),
        SR("A person with no political voice must be able to become personally significant -- worth a scene, worth a decision -- purely through the discovered effect of her private labor, without her ever taking a public political action herself.",
           "This is the entire shape of her possible story: she never speaks, organizes, or leads. Her only interface to the world's politics is what other people find in her workshop.",
           "core"),
        SR("Her season must be able to end through means that require no institutional process at all -- being found and killed, or simply vanishing -- not only through an arrest, trial, or faction-tree escalation.",
           "A person outside every institution's ledger (no Standing, no faction officer role, no Disposition floor anywhere) has no guaranteed institutional off-ramp; if the engine only models exits via faction-scale processes, hers has none available.",
           "important"),
        SR("The engine must represent something about a season of her life beyond identity-only reference data -- some tracked state that a player interaction can actually change -- for at least the season in which she is engaged.",
           "The NPC tracking-tier system defaults an NPC with no faction leadership and no fired priority-tree action to a tier with no tracked Disposition or state, existing only as a name in generated text. By the letter of that rule, nothing about a season of her life is tracked at all unless something promotes her out of it -- which is the exact question this case exists to test.",
           "core"),
        SR("A single scene of investigation, discovery, or protection involving her must be able to permanently change a persistent fact about her (protected / exposed / arrested / dead) that carries forward into subsequent seasons.",
           "Without persistence of outcome, a discovery-driven resolution resets every season and the case never actually concludes.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing",
        "needs_memory_of": "whether she has been discovered, protected, exposed, or killed in a prior season; how many copies exist and where they are; her accumulated contribution to institutional attention, if any.",
        "needs_deadline": "no",
    },
    "who_acts": ["Carin Vedel", "any Church Inquisitor investigating the region", "Restoration Movement leadership, insofar as they decide whether to protect or use her", "the player"],
    "knowledge": [
        "whether the Church knows a copyist is active in a given territory",
        "whether the player knows she exists at all -- the source names no discovery mechanism absent a scene",
        "whether other Restoration Movement members know the location of her copies",
    ],
    "ends_when": "never automatically -- only by discovery, arrest, or death, or by a player-driven resolution; the source names no natural conclusion.",
})

# ---------------- NPC-087 Uwe Askeland ----------------
cases.append({
    "id": "NPC-087",
    "name": "Uwe Askeland",
    "one_line": "A hedge-school teacher running illegal Einhir education in the southwest, holding no post beyond the classroom he keeps hidden.",
    "scale": "person",
    "season_requires": [
        SR("A person with no office must be able to run a recurring, location-bound activity whose ongoing existence -- not any single completed task -- is itself the thing at stake.",
           "The source frames this as a standing condition ('illegal Einhir education'), not a discrete completed task; if the engine only models discrete finished actions, there is nothing to represent him as 'still doing' from season to season.",
           "core"),
        SR("The material he teaches must be classified as suppressed cultural/political knowledge, retainable by ordinary non-sensitive minds, rather than Thread-substrate knowledge subject to the setting's epistemological barrier.",
           "If Einhir cultural/language instruction is instead the kind of knowledge that is mechanically unstable in non-sensitive minds, his students forget what he teaches regardless of his skill, and the premise of an effective hedge school collapses. The source does not explicitly place this content on one side of that line or the other.",
           "core"),
        SR("The cumulative effect of many small private teaching sessions must be able to aggregate into a settlement- or territory-scale outcome without Askeland himself possessing the faction-level resources that the only named aggregation mechanism for this kind of cultural effect requires.",
           "The one named mechanism for Restoration cultural effect at territory scale is a faction Domain Action costing a Mandate+Influence pool; a lone teacher holds neither. UNCLEAR whether or how his labor connects to that mechanic at all.",
           "important"),
        SR("His discovery must be able to branch three ways for whoever finds him -- protect him, report him, or leverage the discovery -- with materially different consequences down each path, not just a binary helped/not-helped outcome.",
           "His arc_trajectory names exactly this branch ('protect/report/leverage'); a binary outcome model has nowhere for the leverage option -- using the discovery as pressure rather than acting on it directly -- to register.",
           "core"),
        SR("A student's exposure (being caught attending, or found to have been taught) must be trackable as a consequence for the student, separate from any consequence for Askeland.",
           "A hedge school has many attendees; if only the teacher can be 'caught,' the shared risk of an illegal communal activity -- families at risk, informants among the students -- has no mechanical footing.",
           "important"),
        SR("He must be reachable by a scene opportunity despite holding no faction Standing, no assigned Duty, and no Disposition floor with any faction leader.",
           "The engine's scene-generation surfaces named NPCs chiefly via Duty-alignment or Outreach gated on a fired faction priority-tree action, neither of which a lone teacher with no institutional position triggers on his own.",
           "core"),
        SR("His activity must be able to persist across seasons completely unwitnessed, and be discoverable later exactly as it would have been discovered earlier -- not silently resolved off-screen the way an unattended faction-generated opportunity is.",
           "Unlike an assigned task (which resolves via NPC AI when unpursued) or an outreach offer (which lapses with a small penalty), his classroom is not his to resolve -- it simply keeps existing until an outside actor engages it. The source's table of what happens to unpursued opportunities has no entry for 'nothing happens, and nothing is supposed to.'",
           "important"),
        SR("UNCLEAR: whether institutional attention toward his activity accumulates through the same channel used for Thread-heresy detection, given that what he teaches (per the need above) may be a caste/political offense rather than a metaphysical one.",
           "The attention-accumulation pipeline the source specifies is built around Thread-heresy detection; whether banned cultural education routes through the same pipeline or a different one is not stated anywhere in the read sources.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing",
        "needs_memory_of": "which students and settlements he has already taught; whether he has been discovered before; cumulative institutional attention his activity has drawn.",
        "needs_deadline": "no",
    },
    "who_acts": ["Uwe Askeland", "his students and their families", "any Church or Crown authority present in the southwest territory", "the player"],
    "knowledge": [
        "whether any authority knows the school exists",
        "whether the player knows he exists -- again, no named discovery path",
        "whether Restoration Movement leadership is aware of or directing him",
    ],
    "ends_when": "never automatically; only via a discovery-driven resolution (protect/report/leverage), or unremarked continuation.",
})

# ---------------- NPC-086 Joren Bergvall ----------------
cases.append({
    "id": "NPC-086",
    "name": "Joren Bergvall",
    "one_line": "A Guild surveyor holding a technical, non-leadership office who has assembled physical evidence that a political conspiracy is actually a Calamity-caused blockage.",
    "scale": "person",
    "season_requires": [
        SR("A technical specialist's field data must be able to exist as a persistent evidence object with its own scope and quality, independent of any single Contest roll -- something that can be examined, copied, corroborated, or suppressed as an artifact.",
           "His entire narrative function is 'has data'; if evidence exists only as the outcome of a single dice roll rather than a persistent object, there is nothing for a second party to independently verify, steal, or destroy.",
           "core"),
        SR("Presenting his evidence to a political audience must be able to change what that audience believes about the cause of the sea-route blockage, and that changed belief must persist and spread to third parties who never saw the data themselves.",
           "The stated payoff of his existence -- undermining a faction's conspiracy narrative -- requires a belief change that outlives the presentation scene and travels beyond the room it happened in.",
           "core"),
        SR("UNCLEAR: whether the causal fact his evidence supports (the blockage is Calamity-caused, not political) is itself Thread-substrate knowledge subject to the setting's epistemological barrier -- if so, a non-sensitive audience cannot stably retain the correct explanation even after being shown the evidence.",
           "Separate world-building sources state plainly that the rational explanation for the blockage is 'literally unrememberable without Thread Sensitivity,' which directly threatens the premise that his data can durably change anyone's mind. The source never specifies whether his evidence proves only the negative fact (the route fails, regardless of cause) or the full causal explanation.",
           "important"),
        SR("A Guild employee below faction-leadership rank must be reachable by a scene opportunity through his technical output becoming relevant to a player, not only through his faction leadership's own political business.",
           "He holds an office but not a leadership seat with a priority tree of his own; the named outreach mechanism for his faction lists only the Guild leadership as a source, so without a content-driven path in, his data can only surface through someone else's business.",
           "important"),
        SR("His findings must be able to be suppressed, altered, or bought before reaching a political audience, by an actor with an interest in the conspiracy narrative persisting.",
           "A one-way 'he has the truth, therefore truth wins' model removes all stakes; the finding's political value only exists if someone can also make it disappear.",
           "important"),
        SR("His personal risk for holding or publishing this data must be trackable as politically motivated, distinct from the Church-heresy detection machinery that governs most other exposure risk in the setting.",
           "Unlike the Restoration/heresy cases, his exposure risk is political (a faction whose founding grievance the data undercuts), not doctrinal; the existing detection/attention machinery is specified around Church heresy and does not obviously cover this vector.",
           "important"),
        SR("Corroborating or refuting his claim must be possible for a third party through independent fieldwork, not only by taking his word for it.",
           "Evidence that cannot be independently checked is an assertion with a fancier name; the case tests whether the engine can represent a contestable physical/empirical claim at all, distinct from a social contest outcome.",
           "core"),
    ],
    "temporal": {
        "span_seasons": "ongoing until his finding is publicly resolved (accepted or discredited) or suppressed",
        "needs_memory_of": "the existence and content of his survey data; whether it has already been shown to anyone; whether the conspiracy narrative has already been challenged as a result.",
        "needs_deadline": "no deadline is named in the source, though a live political controversy implies urgency is possible.",
    },
    "who_acts": ["Joren Bergvall", "Guild leadership (whether they let him publish or suppress)", "the faction whose founding narrative the data threatens", "the player"],
    "knowledge": [
        "whether that faction's leadership knows the true cause of the blockage",
        "whether the general population retains the causal explanation once told, given the Forgetting question above",
        "whether Guild leadership is aware of what he has found",
    ],
    "ends_when": "never explicitly stated; presumably when the conspiracy narrative is durably dispelled or the data is destroyed or discredited.",
})

# ---------------- NPC-075 Orm ----------------
cases.append({
    "id": "NPC-075",
    "name": "Orm",
    "one_line": "The second-ranking Warden at the dying Southernmost outpost, thirty-one years into an unrewarded war of attrition against the Calamity's aftermath, answering to no faction.",
    "scale": "person",
    "season_requires": [
        SR("A person's decision to continue an exhausting, unrewarded maintenance labor (repairing breaches in the world's substrate) must be represented as a real season-to-season choice, including the possibility that he stops, burns out, or dies at it.",
           "His arc_trajectory is explicitly about how his service ends (a death that permanently seals a breach); the case only exists if the labor and its cost are actually adjudicated each season, not assumed as background fact.",
           "core"),
        SR("A practitioner's ongoing exposure to the substrate damage he repairs must be able to degrade his personal condition cumulatively across many seasons, distinct from the cost of any single act of repair.",
           "Canon states the specific repair operation he performs costs him nothing directly per use, but that Warden degradation is environmental -- proximity to damage sites, not a function of the repair operation itself -- so thirty-one years of exposure must be tracked as its own slow-accruing cost, separate from his actions.",
           "core"),
        SR("His death, if it occurs while performing a repair, must be able to produce a different and better outcome for the world than the same repair performed by someone who lives.",
           "His arc_trajectory names exactly this asymmetry; the case tests whether the engine can represent a deliberate self-sacrifice as mechanically distinct from an equivalent non-lethal success, not merely as flavor text on an identical outcome.",
           "core"),
        SR("A subordinate rank within a tiny, non-political, non-recruiting institution must be trackable as a real position with real relationships (a senior to answer to, peers to lose) even though the institution has no faction stats, no Domain Actions, and no seat at any political table.",
           "He specifically holds a named rank under a named senior -- a hierarchy implies a chief he serves under; if the engine only tracks entities that participate in faction-level play, a purely internal office in a non-playing institution has nothing to attach to.",
           "important"),
        SR("The cumulative consequence of every other faction's warfare and Thread-disruptive activity anywhere on the peninsula must be able to reach him personally as an accumulating burden, without him ever having interacted with those factions.",
           "Canon states that any faction's Thread-disturbing activity registers as substrate strain the Wardens absorb regardless of source; his season is shaped by remote actions he has no way to prevent or necessarily perceive the origin of.",
           "core"),
        SR("His decades of specific field experience with a defined category of threat must make him mechanically superior at that category of action compared to someone without the experience, not merely narratively described as expert.",
           "The archetype invoked for him implies specialized, hard-won competence; if thirty-one years produce no measurable mechanical advantage over a novice, the years are decorative rather than load-bearing.",
           "important"),
        SR("A player who reaches him must be able to have access gated by demonstrated Thread competence rather than by faction standing, reputation, or wealth -- none of which his institution recognizes.",
           "The parallel file for his institution's chief states access is gated purely by demonstrated Thread Sensitivity and competence; Orm, sharing the same institution's values, needs the identical non-political gate, or his no-office status is meaningless -- political leverage would smuggle back in.",
           "important"),
        SR("UNCLEAR: the only detailed source for the state-machine map of his arc (analogous to the one that exists for his institution's chief) is a document that has since been moved out of the live source tree, so no season-level detail beyond one summary sentence is available to extract.",
           "This is a real sourcing gap, not an inferred one -- the tree's own path-resolution ledger confirms the document is no longer on the branch read here; anything beyond the registry's one-line arc description is unverifiable from the current sources.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing (decades-long service, per '31 years'), until death or the outpost's collapse",
        "needs_memory_of": "his accumulated exposure/degradation; how many breaches he has personally sealed; his standing relative to his senior and any other Wardens; whether his death-in-service arc has already triggered.",
        "needs_deadline": "no fixed date, but implicitly bounded by the world's substrate stability, which worsens on its own independent clock.",
    },
    "who_acts": ["Orm", "the Warden-Chief (his senior)", "every faction whose Thread-disruptive activity anywhere on the peninsula adds to his burden", "the player, if and when access to the outpost is earned"],
    "knowledge": [
        "whether any non-Warden actor knows he exists at all -- the Wardens are below every major faction's notice",
        "whether his senior or the other Wardens know the true state of his personal degradation",
        "whether a player has earned enough demonstrated competence to be acknowledged by him",
    ],
    "ends_when": "his death (possibly a deliberate death-in-service act), the outpost's fall, or -- per the sourcing gap above -- an undefined further state.",
})

# ---------------- NPC-005 Sigrid Torsvald ----------------
cases.append({
    "id": "NPC-005",
    "name": "Sigrid Torsvald",
    "one_line": "A covert military-order operative whose official record and personal reality have diverged -- she does not officially exist, and neither does the Thread Sensitivity she has secretly developed.",
    "scale": "person",
    "season_requires": [
        SR("An act she performs must be able to leave no attributable trace back to her, her order, or her Crown when it succeeds cleanly -- full deniability as an achievable outcome, not merely a stated intention.",
           "Officially not existing is meaningless unless clean, traceless success is a real, reachable state distinct from success-with-a-trail; otherwise every mission is secretly a liability regardless of outcome.",
           "core"),
        SR("An act that goes partially wrong must be able to generate a persistent, accumulating institutional risk that is distinct from, and outlives, the scene in which it happened, and that risk must be able to cross a threshold that forces consequences later, in a different season, for a different reason.",
           "This is the specified shape of her institution's covert-risk mechanic: partial results and failures accrue a debt that later triggers exposure, an inquiry, or a forced demotion -- none of which are visible at the moment of the original mission.",
           "core"),
        SR("Her private reputation among people who can never publicly credit her (fellow operatives, informants, a patron) must be trackable and consequential, on a track separate from any reputation she could have in ordinary faction life.",
           "A covert operative's reputation is specified as a parallel, non-public track from ordinary public standing; collapsing them into one number erases her defining condition -- valued but unable to be seen as valuable.",
           "core"),
        SR("A perception or capability she secretly has (Thread Sensitivity) must be able to be true and mechanically active while remaining completely unknown to the institution she serves, with that institution's own rules treating mere discovery of the secret as automatically disqualifying, regardless of her competence or loyalty.",
           "Canon states her order would consider her compromised 'not because they think TS is evil, but because they cannot trust that her perception of reality is the same as theirs' -- the disqualification is about the secrecy and divergence itself, not a judgment on the trait, and that distinction has to be preserved for her core conflict to exist.",
           "core"),
        SR("A refusal to accept a mission must be able to cost her standing even when her reasons (avoiding harm only she can perceive) are sound -- the institution's cost model cannot be sensitive to whether her private judgment was actually correct.",
           "Canon specifies that her rank must 'accept any mission; no refusals' on pain of accruing institutional debt -- this is exactly what produces her described behavior of risk aversion under a doctrine that punishes exactly that aversion.",
           "important"),
        SR("Her perception of the consequences of a mission must be able to diverge from her colleagues' and superiors' assessment of that same mission -- the identical event scored as a clean win institutionally and as a partial disaster by her personal standard.",
           "This dual assessment is the entire point of giving her a perceptual capacity her colleagues lack; a single shared outcome-quality score for the mission would erase the perceptual gap that defines her.",
           "core"),
        SR("A prior personal relationship formed years earlier (guarding an archive for someone she has since stayed connected to) must be able to resurface and pull her into a scene later, creating a genuine conflict between her covert obligations and that relationship.",
           "Source material names this connection as the hinge of her larger arc; the mechanism must support a past-tense relationship becoming present-tense pressure, not remain a static biography note.",
           "important"),
        SR("If her covert status is exposed publicly, the consequence must convert what she gained secretly into an explicit, larger public loss, rather than simply erasing the secret gain.",
           "Canon specifies that a publicly exposed covert gain converts into public loss plus additional institutional debt -- an asymmetric penalty, not a wash -- which is what makes exposure something to be feared beyond 'the secret is out.'",
           "important"),
        SR("Her overt institutional rank and her covert rank must be able to move independently -- advancement or disgrace in one must not automatically imply the same in the other.",
           "Canon runs two explicit, separate rank ladders for the same person; collapsing them into one track would make 'publicly respected, privately compromised' impossible to represent.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing",
        "needs_memory_of": "her accumulated institutional risk debt; her private covert-reputation track; her current, hidden practitioner condition; the status of her old archive connection; whether her Thread Sensitivity has ever been discovered by anyone.",
        "needs_deadline": "no fixed date; escalation is threshold-driven rather than calendar-driven.",
    },
    "who_acts": ["Sigrid Torsvald", "her covert order's commander (assigns missions, can override her)", "the archive-owner she is still connected to", "her order's overt leadership (would react to exposure)", "the player"],
    "knowledge": [
        "whether her order knows she is Thread Sensitive (currently: no)",
        "whether any given mission's institutional record matches what actually happened",
        "whether the archive-owner is aware of what her time with the archive did to her",
        "whether the player has learned of her covert status at all",
    ],
    "ends_when": "never explicitly stated; presumably her exposure and its institutional fallout, her death, or a resolution of the archive-connection arc -- none of which the source specifies as a defined final mechanical state.",
})

# ---------------- NPC-010 Dalla Virke ----------------
cases.append({
    "id": "NPC-010",
    "name": "Dalla Virke",
    "one_line": "An independent broker in illicit antiquities and information who profits from relationships no institution can requisition, and who has personally certified goods she did not know were dangerous.",
    "scale": "person",
    "season_requires": [
        SR("A non-faction, non-institutional actor must be able to hold and trade a resource (information, trust, access) that no faction's own action economy owns or produces -- a market that exists outside every faction's resource pools.",
           "Her entire value proposition is relational trust as capital, distinct from any faction's wealth/mandate/influence tracks; if her trading only shows up as a modifier on someone else's faction stat, there is no independent economy for her to be the actor within.",
           "core"),
        SR("Information she sells must be able to be true, false, or fabricated, with the buyer unable to distinguish which in advance, and her incentive to fabricate must rise specifically when honest demand for information falls.",
           "The settlement-level mechanic for independent information brokers explicitly states they 'fabricate intel when peace reduces demand' -- a broker who always sells accurate information isn't modeling an information economy, just a lookup table.",
           "core"),
        SR("She must be discoverable, killable, buyable, or turnable by an outside actor as four textually distinct outcomes with different consequences for her network, not variations on one generic 'remove her' resolution.",
           "The canonical mechanic for settlement-level brokers lists exactly these four fates; each implies a different result for her trust network (destroyed, inherited, redirected, or compromised from within), and the case tests whether the engine actually distinguishes them.",
           "core"),
        SR("Her personal judgment about a specific past transaction (vetting goods as safe and legitimate) must be able to be wrong in a way that is discoverable later and attributable specifically to her, not to an abstract 'the network' or 'the market.'",
           "Her defining compromise is that she personally selected and vetted a dangerous supply chain she did not understand; this requires the engine to attribute a specific past transaction to a specific person's judgment, not generic 'illicit goods exist' flavor.",
           "core"),
        SR("A revelation that damages her standing with one party (a partner learning she shields certain clients from her own family's operations) must be able to threaten her position with a different party (her family) whose interests and knowledge are entirely separate.",
           "Her arc is explicitly two-sided -- trusted by clients, answerable to family -- and these are separate relationships that can each independently collapse; a single reputation score cannot represent being simultaneously trusted by one audience and one exposure away from replacement by another.",
           "important"),
        SR("Her removal (replacement by someone with no local relationships) must be able to collapse benefits that other, unrelated actors were quietly relying on, in the same season, as a single cascading event rather than isolated losses each requiring its own trigger.",
           "Her removal is framed as a peninsula-wide disruption precisely because many factions' discreet arrangements were riding on her personally; the case tests whether one person's removal can propagate to simultaneous effects on third parties who never touched the triggering event.",
           "important"),
        SR("Trading in goods whose true dangerous nature is unknown even to the seller must be able to produce consequences later, when the nature becomes known, that attach retroactively to the original transaction rather than only affecting future trades.",
           "Her exposure risk hinges on a past sale being revealed as more dangerous than believed at the time; if only forward-looking trades can carry this risk, her signature compromise -- a supply chain she already built -- has nothing to activate.",
           "important"),
        SR("UNCLEAR: reaching her for a player with no criminal or covert affiliation must be possible through some channel other than the adversarial 'discover a hostile intelligence asset' mechanism used to find brokers, since she is specifically framed as approachable rather than merely detectable.",
           "The only named discovery path for settlement-level brokers is adversarial; the source does not specify a parallel path for a player who wants to hire or ally with her rather than expose her.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing",
        "needs_memory_of": "every prior transaction she has personally vetted and its true, possibly still-unknown nature; her standing with her family; which factions currently rely on her network and for what.",
        "needs_deadline": "no explicit deadline; risk is exposure-driven, not calendar-driven.",
    },
    "who_acts": ["Dalla Virke", "her trading partners across factions", "her family (can recall or replace her)", "the Guild figure linked to her through the same exposure chain", "the player"],
    "knowledge": [
        "whether anyone, including Virke herself, knows which goods in her supply chain are dangerous",
        "whether her family knows she shields certain clients from their operations",
        "whether any faction has discovered her broker role",
    ],
    "ends_when": "never explicitly named; presumably her exposure or recall event, or indefinite continuation.",
})

# ---------------- NPC-012 Rikard Solberg ----------------
cases.append({
    "id": "NPC-012",
    "name": "Rikard Solberg",
    "one_line": "A foreign trade official whose homesickness has been unconsciously steering an entire nation's peninsula policy toward the one outcome -- Valorian stability -- that would let him go home.",
    "scale": "person",
    "season_requires": [
        SR("A single office-holder's personal, unstated motive must be able to measurably bias every decision he makes in that office, in one consistent direction, without him or his superiors recognizing the pattern.",
           "The character is built entirely on this: he does not know he is doing this. Every one of his professional recommendations is individually defensible but collectively wrong for his stated employer.",
           "core"),
        SR("His employer's institutional evaluation of him must be able to stay positive -- he is 'too valuable to recall' -- specifically because of the state of the world he is unconsciously prolonging, a closed loop between his output and his own continued posting.",
           "The mechanism that traps him requires his competent-seeming service to be the reason he stays, not despite it; if his bias simply read as poor performance, his superiors would replace him and the case collapses into ordinary incompetence.",
           "core"),
        SR("A player who identifies his true motive must be able to offer him something categorically different from a bribe or a threat -- a real, verifiable path to recall -- and have that offer change his behavior, with the engine able to distinguish a genuine offer from a false one via his own judgment.",
           "The source is explicit that the offer 'must be real. Solberg is not stupid and will not believe a false promise' -- the case tests whether an NPC's cooperation can be conditioned on verifying the substance of an offer, not just its social presentation.",
           "core"),
        SR("His own faction's strategic decision-making must be able to independently recall or replace him based on faction-scale conditions, entirely apart from any player action.",
           "Canon specifies his faction's own priority tree recalls him once two or more of a named set of conditions hold -- his season can end through his own institution's ordinary functioning, with no player or scene required.",
           "important"),
        SR("If he is replaced, his successor's behavior must differ measurably from his (more aggressive arms flows, sharper intelligence, harsher trade terms) as a direct consequence of removing his specific bias, not merely a new NPC with the same name.",
           "The source explicitly quantifies what an unbiased replacement would do differently; his removal has to actually change downstream faction behavior for the case to mean anything.",
           "important"),
        SR("His private, non-work relationships (his children, growing up without him) must be able to exist as a motivating fact even though they are physically absent from every scene he could appear in on the peninsula.",
           "His motive is entirely sourced from people who are never present and never interact with any mechanic directly; the engine must support a motivating relationship with zero on-screen mechanical footprint of its own.",
           "flavour"),
        SR("His institutional loyalty and the effect of his actions must be able to diverge permanently without him ever consciously betraying or defecting from his employer.",
           "This is explicitly not a defection arc -- he believes his recommendations serve his employer the whole time; the case tests whether sincere loyalty producing objectively disloyal outcomes is representable as a stable, non-resolving state rather than something that must eventually collapse into either loyalty or betrayal.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing, bounded by a possible recall (self-triggered by his faction, or player-brokered)",
        "needs_memory_of": "his accumulated years on posting; whether a player has identified and acted on his motive; the current state of his faction's named recall conditions.",
        "needs_deadline": "no fixed date; recall is threshold-driven, not calendar-driven.",
    },
    "who_acts": ["Rikard Solberg", "his home nation's central leadership (recalls him via its own strategic priorities)", "the player (can offer him a real path to recall)", "every faction his arms/intelligence/trade recommendations touch"],
    "knowledge": [
        "whether his home nation's leadership has noticed his bias",
        "whether the player has correctly diagnosed his motive -- the source notes this is discoverable through ordinary investigation",
        "whether any offer made to him is verifiably real",
    ],
    "ends_when": "his recall, by his own nation or via a player-brokered genuine stability treaty, or indefinite continuation of the status quo.",
})

# ---------------- NPC-002 Maret Uln ----------------
cases.append({
    "id": "NPC-002",
    "name": "Maret Uln",
    "one_line": "A practitioner and intelligence operative whose lived perception of the population she surveils is eroding the professional discipline her work requires, and who is the sole named successor if her patron falls.",
    "scale": "person",
    "season_requires": [
        SR("Performing a Thread operation as part of ordinary intelligence work must cost the practitioner a persistent personal resource whose cost scales with the scale and type of operation performed, distinct from whether the operation succeeded.",
           "Canon's operation-cost model makes this the central mechanical fact of being a practitioner; an intelligence operative who is also a practitioner must pay this cost on top of, and separately from, ordinary fieldwork detection risk.",
           "core"),
        SR("As her personal condition degrades across a season, the range of actions available to her must narrow in a fixed, predictable order -- from full freedom down to forced withdrawal and crisis -- and that narrowing must override her institutional orders when the two conflict.",
           "Canon's practitioner decision-threshold table specifies exactly this ladder and states that self-limiting survival rules apply regardless of institutional loyalty at the bottom of it; her employer's demands cannot force her past what her own condition allows.",
           "core"),
        SR("Her personal sympathy for a population she is ordered to act against must produce a measurable, repeatable delay or softening in her actions against that population, distinct from a single one-time refusal.",
           "Canon specifies this precisely as a standing one-season delay pattern, not a single dramatic moment of conscience.",
           "core"),
        SR("UNCLEAR: the two live canonical sources for her Thread Sensitivity disagree (one states roughly 50, the other states 35), and this is not a cosmetic discrepancy -- the two values sit in different tiers of the setting's own sensitivity banding, which changes how much strain her presence imposes on everyone close to her, every season.",
           "If the engine must pick one value to run her season, the two sources do not agree on which tier she occupies, and that tier directly changes the mechanical cost her existence places on every NPC or PC with a close relationship to her.",
           "important"),
        SR("A designated successor to a faction leader must exist as a real, trackable status -- with defined behavioral constraints relative to the current leader -- well before succession ever actually happens, not only as a rule that activates once on the leader's death.",
           "Canon specifies succession-mode behavioral constraints on her as though they are already partly present, implying the fallback identity shapes her behavior in advance of the triggering event, not only after it.",
           "important"),
        SR("If her patron is eliminated and she inherits leadership, a faction-level clock tied specifically to her predecessor's personal project must be able to reset to zero rather than simply transferring to her.",
           "Canon states her succession resets her predecessor's personal intelligence-infrastructure clock, representing that his personally accumulated work -- not just his office -- is lost; the engine must distinguish a leader's personal accumulated asset from the office's ongoing resources, since only one survives the transition.",
           "important"),
        SR("Her intelligence-gathering must be able to produce results that are qualitatively richer than ordinary reconnaissance -- direct experiential perception of substrate-level damage, not reported facts -- meaning what she knows about a target population must be represented as more than an abstract evidence value.",
           "Source material is explicit that 'her intelligence is not data points -- it is lived experience'; if the engine only stores intelligence as an abstract number, this qualitative distinction, and the toll it takes on her, has nothing to attach to.",
           "important"),
        SR("A season in which she takes no visible action against her own sympathies must still register as a choice with consequences (an opportunity cost to her faction), not as a null default outcome.",
           "Her hesitation is professionally costly to her faction even though nothing dramatic happens on-screen in the seasons she hesitates; the engine needs to charge a cost for inaction specifically tied to her divided loyalty, not only for failed actions.",
           "important"),
    ],
    "temporal": {
        "span_seasons": "ongoing, contingent (succession-mode behavior activates only if/when her patron is eliminated)",
        "needs_memory_of": "her accumulated personal condition; her cumulative hesitation pattern against the population she sympathizes with; whether her patron is still alive; if he has fallen, whether she has formally inherited.",
        "needs_deadline": "no fixed date for the succession trigger, but her personal condition's decay and recovery are themselves season-paced.",
    },
    "who_acts": ["Maret Uln", "her patron (whose fall triggers her succession mode)", "the population she surveils and sympathizes with", "the player"],
    "knowledge": [
        "whether her patron knows the extent of her sympathy for the population she surveils",
        "whether that population knows her faction's surveillance of them is consistently delayed because of her, specifically",
        "her own private assessment of that population's activity versus what she reports upward -- a gap between what she knows and what she tells",
    ],
    "ends_when": "never explicitly named as a terminus; presumably resolved only when she defects, successfully compartmentalizes, or her patron falls and she inherits.",
})

print(yaml.safe_dump(cases, sort_keys=False, allow_unicode=True, width=100, default_flow_style=False))
