"""
doc_index_gen.py — Generate _index.md files from canonical design docs.

Pure function: no GitHub I/O. Caller provides content, receives index string.

Renamed from skeleton_gen.py in PP-673 to resolve terminology collision:
  - "skeleton" = canonical ruleset in mechanical-only style (banner-labeled)
  - "index" = auto-generated heading/line/token table for navigation
This tool generates INDEXES, not skeletons.
"""

import re
from datetime import datetime, timezone


def generate_index(canonical_path: str, canonical_content: str,
                   canonical_sha: str = "unknown") -> str:
    """
    Returns index content: heading tree + line ranges + token count per section.

    Format:
      <!-- INDEX metadata -->
      # {basename} — Index
      ## Heading Index (table)
      ## Section Sizes (table)
    """
    lines = canonical_content.splitlines()
    total_tokens = len(canonical_content) // 4
    basename = canonical_path.rsplit("/", 1)[-1].replace(".md", "")

    headings = []
    for i, line in enumerate(lines):
        m = re.match(r'^(#{1,6})\s+(.+)', line)
        if m:
            headings.append({
                'idx': len(headings),
                'line': i + 1,
                'level': len(m.group(1)),
                'text': m.group(2).strip(),
            })

    # Compute section sizes (each heading → next same-or-higher level heading)
    section_sizes = []
    for i, h in enumerate(headings):
        start = h['line'] - 1
        end = len(lines)
        for j in range(i + 1, len(headings)):
            if headings[j]['level'] <= h['level']:
                end = headings[j]['line'] - 1
                break
        section_content = "\n".join(lines[start:end])
        section_sizes.append(len(section_content) // 4)

    # Build index
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    sha_short = canonical_sha[:12] if canonical_sha != "unknown" else "unknown"

    parts = [
        f"<!-- INDEX — auto-generated by doc_index_gen.py -->",
        f"<!-- canonical: {canonical_path} -->",
        f"<!-- canonical_sha: {sha_short} -->",
        f"<!-- canonical_tokens: {total_tokens} -->",
        f"<!-- generated: {now} -->",
        "",
        f"# {basename} — Index",
        "",
        f"**Usage:** `g.read_sections('{canonical_path}', [indices])` to load specific sections.",
        "",
        "## Heading Index",
        "",
        "| Idx | Line | Level | Heading |",
        "|-----|------|-------|---------|",
    ]

    for h in headings:
        parts.append(f"| {h['idx']} | {h['line']} | {h['level']} | {h['text']} |")

    parts.append("")
    parts.append("## Section Sizes (tokens)")
    parts.append("")
    parts.append("| Idx | Tokens | Heading |")
    parts.append("|-----|--------|---------|")

    for i, h in enumerate(headings):
        tokens = section_sizes[i] if i < len(section_sizes) else 0
        parts.append(f"| {h['idx']} | {tokens:,} | {h['text']} |")

    return "\n".join(parts) + "\n"


def needs_regeneration(canonical_path: str, canonical_sha: str,
                       index_content: str) -> bool:
    """
    True if index is missing, SHA mismatch, or canonical content changed.
    """
    if not index_content:
        return True
    existing_sha = extract_canonical_sha(index_content)
    if existing_sha is None:
        return True
    # Compare abbreviated SHAs (12 chars)
    return existing_sha[:12] != canonical_sha[:12]


def extract_canonical_sha(index_content: str) -> str | None:
    """Parse 'canonical_sha: XXX' from index header."""
    m = re.search(r'<!-- canonical_sha:\s*(\S+)\s*-->', index_content)
    return m.group(1) if m else None


def index_path_for(canonical_path: str) -> str:
    """Derive index path from canonical path: foo.md → foo_index.md"""
    if canonical_path.endswith(".md"):
        return canonical_path[:-3] + "_index.md"
    return canonical_path + "_index.md"


# ── CLI test ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    sample = """# Test Doc

## Section A

Some content here spanning
multiple lines with detail.

## Section B

### Subsection B1

More content.

## Section C

Final section.
"""
    result = generate_index("designs/test_doc.md", sample, "abc123def456")
    print(result)
    print("---")
    print(f"needs_regen (match): {needs_regeneration('x', 'abc123def456', result)}")
    print(f"needs_regen (mismatch): {needs_regeneration('x', 'zzz999', result)}")
    print(f"extract_sha: {extract_canonical_sha(result)}")
