#!/usr/bin/env python3
"""definitions_store.py — the unified definitional surface (Repository State Armature, Phase 2, ED-IN-0077).

ONE place to retrieve any definition. The store (`references/definitions/definitions.yaml`) is a
GENERATED merge of the two keyed authoritative registers — `references/names_index.yaml` (the
canonical name / aliases / legacy / enforce, per its own header "the one place a name lives") and
`references/descriptor_registry.yaml` (the pointer roster: scale + grouping). One record per dotted
key, so a term's name, scale, category, enforcement and provenance are legible in a single row.

CAREFUL BY DESIGN — nothing is rewired:
  * The store is a *generated view*, not a new source. names_index stays authoritative for names
    (ci_names_consistency already asserts descriptor_registry mirrors it); this module extends that
    same discipline to a full record, it does not invert generation. The eventual inversion (registers
    generated FROM the store) is a separate, parity-gated follow-up — see repo_state_armature_v1.md §5 P2.
  * `--check` is the drift gate: the committed store must equal a fresh rebuild, AND every overlapping
    key's canonical must agree across the two registers. It also SURFACES (does not fabricate over) the
    keys that live in only one register — the real fragmentation this unification exists to make legible.

CLI:
  python3 tools/definitions_store.py --build          # regenerate the store from the registers
  python3 tools/definitions_store.py --check           # drift + parity gate (exit 1 on drift/mismatch)
  python3 tools/definitions_store.py --get attr.body.will
  python3 tools/definitions_store.py --search will      # substring over key/canonical/aliases/legacy
  python3 tools/definitions_store.py --list [--category attribute]
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
NAMES = ROOT / "references" / "names_index.yaml"
DESCRIPTORS = ROOT / "references" / "descriptor_registry.yaml"
STORE = ROOT / "references" / "definitions" / "definitions.yaml"

_HEADER = """\
# GENERATED by tools/definitions_store.py --build — DO NOT EDIT BY HAND.
# The unified definitional surface (Repository State Armature Phase 2, ED-IN-0077): one record per
# dotted key, merging references/names_index.yaml (canonical/aliases/legacy/enforce — authoritative
# for names) + references/descriptor_registry.yaml (scale/grouping). Retrieve any definition from
# here: `python tools/definitions_store.py --get <key>`. Drift-locked: `--check` asserts this equals
# a fresh rebuild and that name fields agree across the source registers (extends ci_names_consistency).
# `in_registers` records provenance; `gap` flags a key present in only one register (surfaced, not fixed).
"""


def _load_names() -> dict:
    d = yaml.safe_load(NAMES.read_text()) or {}
    return d.get("entries") or {}


def _load_descriptors() -> dict:
    """Flat {dotted_key: {name, aliases, scale, group, category}} across every descriptor section."""
    d = yaml.safe_load(DESCRIPTORS.read_text()) or {}
    out: dict[str, dict] = {}
    attrs = d.get("attributes") or {}
    for grp in ("body", "mind", "social"):
        for e in (attrs.get(grp) or []):
            out[e["key"]] = {"name": e.get("name"), "aliases": e.get("aliases") or [],
                             "scale": attrs.get("scale"), "group": grp, "category": "attribute"}
    for e in ((d.get("aggregates") or {}).get("entries") or []):
        out[e["key"]] = {"name": e.get("name"), "aliases": [], "scale": e.get("compute"),
                         "group": e.get("status"), "category": "aggregate"}
    for section, cat in (("practitioner_stats", "practitioner_stat"), ("territory_stats", "territory_stat"),
                         ("faction_stats", "faction_stat"), ("settlement_stats", "settlement_stat")):
        for e in ((d.get(section) or {}).get("entries") or []):
            out[e["key"]] = {"name": e.get("name"), "aliases": e.get("aliases") or [],
                             "scale": e.get("scale"), "group": None, "category": cat}
    return out


def build() -> dict:
    """Merge the two registers into one record per key. Faithful union — no key invented or dropped."""
    names, desc = _load_names(), _load_descriptors()
    defs: dict[str, dict] = {}
    for key in sorted(set(names) | set(desc)):
        n, dd = names.get(key), desc.get(key)
        in_regs = ([("names_index")] if n else []) + (["descriptor_registry"] if dd else [])
        rec = {
            "canonical": (n or {}).get("canonical") if n else (dd or {}).get("name"),
            "aliases": sorted(set((n or {}).get("aliases") or []) | set((dd or {}).get("aliases") or [])),
            "legacy": (n or {}).get("legacy") or [],
            "category": (n or {}).get("category") if n else (dd or {}).get("category"),
            "enforce": (n or {}).get("enforce") if n else None,
            "scale": (dd or {}).get("scale"),
            "group": (dd or {}).get("group"),
            "in_registers": in_regs,
        }
        # Only the descriptor-only direction is a real inconsistency: a stat in the roster that the
        # authoritative name index doesn't carry. names_index-only is normal — most named things
        # (proper nouns, mechanics, substrate) legitimately have no descriptor scale, so not a gap.
        if dd and not n:
            rec["gap"] = "descriptor-only (not in names_index)"
        defs[key] = {k: v for k, v in rec.items() if v not in (None, [], "")}
    return {"version": 1,
            "generated_from": ["references/names_index.yaml", "references/descriptor_registry.yaml"],
            "count": len(defs), "definitions": defs}


def _serialize(store: dict) -> str:
    body = yaml.safe_dump(store, sort_keys=True, default_flow_style=False, allow_unicode=True, width=100)
    return _HEADER + body


def write_store() -> Path:
    STORE.parent.mkdir(parents=True, exist_ok=True)
    STORE.write_text(_serialize(build()))
    return STORE


def load_store() -> dict:
    return yaml.safe_load(STORE.read_text()) or {}


def check() -> tuple[bool, list[str]]:
    """Drift + parity gate. Returns (ok, messages). Never raises on a normal mismatch."""
    msgs: list[str] = []
    ok = True
    # 1. drift: committed store must equal a fresh rebuild
    fresh = _serialize(build())
    if not STORE.exists():
        return False, ["definitions.yaml missing — run `definitions_store.py --build`"]
    if STORE.read_text() != fresh:
        ok = False
        msgs.append("DRIFT: committed definitions.yaml != fresh rebuild — run --build and commit")
    # 2. name parity on the overlap (extends ci_names_consistency to the store)
    names, desc = _load_names(), _load_descriptors()
    mismatches = 0
    for key in sorted(set(names) & set(desc)):
        cn, dn = (names[key] or {}).get("canonical"), (desc[key] or {}).get("name")
        if cn != dn:
            mismatches += 1
            msgs.append(f"NAME MISMATCH {key}: names_index='{cn}' vs descriptor_registry='{dn}'")
    if mismatches:
        ok = False
    # 3. surface coverage gaps (informational — pre-existing fragmentation, not a --check failure)
    gaps = sorted(set(desc) - set(names))
    if gaps:
        msgs.append(f"[coverage] {len(gaps)} descriptor key(s) absent from names_index: {gaps}")
    return ok, msgs


def _fmt(key: str, rec: dict) -> str:
    bits = [f"  {key}", f"    canonical : {rec.get('canonical')}"]
    for f in ("aliases", "legacy", "category", "enforce", "scale", "group", "in_registers", "gap"):
        if rec.get(f) not in (None, [], ""):
            bits.append(f"    {f:9}: {rec[f]}")
    return "\n".join(bits)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--get", metavar="KEY")
    ap.add_argument("--search", metavar="TERM")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--category", metavar="CAT")
    args = ap.parse_args(argv)

    if args.build:
        p = write_store()
        s = load_store()
        print(f"wrote {p} — {s.get('count')} definitions")
        return 0
    if args.check:
        ok, msgs = check()
        for m in msgs:
            print(("  " if m.startswith("[") else "  - ") + m, file=sys.stderr if not ok else sys.stdout)
        if ok:
            print(f"[DEFINITIONS] store current · {load_store().get('count')} definitions · name parity OK")
            return 0
        print("[DEFINITIONS] FAILED — see above", file=sys.stderr)
        return 1
    defs = (load_store().get("definitions") or {}) if STORE.exists() else {}
    if args.get:
        rec = defs.get(args.get)
        if not rec:
            print(f"no definition for '{args.get}'", file=sys.stderr)
            return 1
        print(_fmt(args.get, rec))
        return 0
    if args.search:
        q = args.search.lower()
        hits = {k: r for k, r in defs.items()
                if q in k.lower() or q in str(r.get("canonical", "")).lower()
                or any(q in str(x).lower() for x in (r.get("aliases") or []) + (r.get("legacy") or []))}
        print(f"{len(hits)} match(es):")
        for k, r in hits.items():
            print(_fmt(k, r))
        return 0
    if args.list:
        rows = [(k, r) for k, r in defs.items() if not args.category or r.get("category") == args.category]
        for k, r in rows:
            print(f"  {k:34} {r.get('canonical','')}  [{r.get('category','')}]")
        print(f"\n{len(rows)} definition(s)" + (f" in category '{args.category}'" if args.category else ""))
        return 0
    print(__doc__)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
