#!/usr/bin/env python3
"""Cook the Key-type registry from prose into typed data. The markdown becomes documentation.

WHY THIS EXISTS.

`systems/_architecture/key_type_registry_v30.md` WAS a **registry parsed at runtime** — until this
tool existed, `TypeRegistry` parsed the prose at load time, and its docstring argued that beat
duplicating the 55-type roster in code. It did. That argument stops holding once the roster has to
reach somewhere Python cannot follow, for three reasons the tree already proves:

(This paragraph deliberately DESCRIBES that former docstring instead of quoting it with a line
number. The commit that created this file also rewrote it, so a quotation here was false on
arrival — the third instance in this programme of correcting a source without sweeping its
quotations, ED-IN-0134/0138. Quoting a file that moves is a self-inflicted staleness generator;
prose about code should describe, or cite something that does not shift.)

1. **Godot re-implements the logic** (Jordan, 2026-08-04) and **cannot parse markdown.** The port's
   answer today is `godot/skeleton/data/key_types/*.tres` — four files, HAND-MADE, covering 4 of 55
   types. A hand shadow of a machine-readable thing is a drift generator; this one is 93% incomplete
   before it has even started drifting.
2. **The roster is already duplicated four ways**, and the duplicates have already diverged:
   `keys.py`'s own docstring said "44-type" for the file it parses (wrong by 11, fixed ED-IN-0134);
   `tools/dashboard_data.py:763-770` runs a SECOND independent parser (a `### ` line counter); and
   `dashboard_data.build_keys()` carries a hand-typed family table. One source, four readers of it,
   and every hand-maintained count drifted.
3. **The goal is python/json-centric** — Python for logic, JSON for data, markdown for information
   paired to a system. A registry is data.

WHAT THIS DOES NOT DO. It does not re-parse the markdown. `TypeRegistry.load()` IS the schema
definition — its tolerant line-based parser (`TypeRegistry._parse_entry`) exists because the registry's
```yaml blocks are prose-flavoured (unquoted colons and parentheticals inside scalars make strict
`yaml.safe_load` fail on real canonical entries). Writing a second parser here would re-commit the
duplication this tool exists to end, so the export calls the live loader and serialises its result.
The markdown stays as the authored, reviewable surface; the JSON becomes what code and Godot read.

ORDER IS LOAD-BEARING. `TypeRegistry.__init__` records that dict order IS registry order (ORD-1). So this
emits keys in REGISTRY ORDER and never sorts them. `json.dumps(..., sort_keys=True)` would be
byte-stabler and would silently destroy an ordering invariant; byte-stability comes from the source
order being deterministic instead.

Usage:
    python3 tools/export_key_types.py            # write engine/engine_params/key_types.json
    python3 tools/export_key_types.py --check    # re-derive and diff vs committed (exit 1 on drift)
"""
from __future__ import annotations

import json
import os
import sys

# Primitives (repo root, lane roster, token estimate, ids, Status reader) are
# owned by tools/ci_common.py — plan G7, ED-IN-0159 §8.3. See its module docstring;
# the two lines below are the bootstrap, anchored on THIS file's directory.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ci_common  # noqa: E402

REPO = ci_common.REPO
sys.path.insert(0, REPO)

from engine.substrate.keys import TypeRegistry  # noqa: E402

SOURCE = os.path.join('systems', '_architecture', 'key_type_registry_v30.md')
OUT = os.path.join('engine', 'engine_params', 'key_types.json')
SCHEMA_VERSION = 1


def build() -> dict:
    """Serialise the live loader's parse. One parser, one schema, no second opinion."""
    reg = TypeRegistry.load(os.path.join(REPO, SOURCE))
    types = reg.types
    if not types:
        raise SystemExit(f"[key-types] {SOURCE} parsed to zero types — refusing to write an empty registry")
    return {
        "_generated": (
            "GENERATED by tools/export_key_types.py from "
            "systems/_architecture/key_type_registry_v30.md via engine.substrate.keys.TypeRegistry. "
            "NEVER hand-edit: re-run the tool. The markdown remains the AUTHORED surface (edit it, "
            "then re-export); this file is what code and the Godot port read. Key order is REGISTRY "
            "order (ORD-1) and is significant — do not sort."
        ),
        "schema_version": SCHEMA_VERSION,
        "source": SOURCE,
        "type_count": len(types),
        "types": types,
    }


def _serialise(doc: dict) -> str:
    # sort_keys=False: ORD-1. See the module docstring.
    return json.dumps(doc, indent=1, ensure_ascii=False, sort_keys=False) + "\n"


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    doc = build()
    text = _serialise(doc)
    out = os.path.join(REPO, OUT)

    if '--check' in argv:
        if not os.path.exists(out):
            print(f"[key-types] MISSING: {OUT} — run `python3 tools/export_key_types.py`")
            return 1
        with open(out, encoding='utf-8') as fh:
            committed = fh.read()
        if committed != text:
            print(f"[key-types] DRIFT: {OUT} does not match a fresh export from {SOURCE}.")
            print("           The markdown is the authored surface; re-run the exporter and commit.")
            # a usable diff, not just a verdict
            import difflib
            for line in list(difflib.unified_diff(
                    committed.splitlines(), text.splitlines(),
                    fromfile='committed', tofile='re-derived', lineterm=''))[:40]:
                print('           ' + line)
            return 1
        print(f"[key-types] round-trip OK — {doc['type_count']} types, {OUT} matches {SOURCE}")
        return 0

    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print(f"[key-types] wrote {OUT} — {doc['type_count']} types (registry order preserved)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
