#!/usr/bin/env python3
"""Export the NPC roster — `engine/season/npcs.yaml` — from the corpus cases.

WHY THIS EXISTS, in Jordan's words (2026-09-13): *"What is the best way to store NPC data? I don't
want these NPCs hard-coded into any simulation/test, but pulled in by those scripts."*

WHAT WAS ALREADY RIGHT, AND WHAT WAS NOT. The 46 NPCs are not hard-coded and never were — they come
from `engine/season/cases/NPC*.yaml`, read at runtime. What WAS code is everything DERIVED about
them: where each one lives, what they want, and who they are tied to were computed by regular
expressions inside `harness/populated.py` on every single run. Three costs, and the third is the
one that matters:

  * you cannot correct ONE NPC without editing matcher code;
  * a change to a matcher moves people SILENTLY, with no diff naming who moved;
  * and the regexes are the authority, so the roster has no reviewable state — which is the
    `CLAUDE.md` §0.05 test failing in the direction it usually fails: the mechanism is real, and it
    is in the wrong place.

THE FORMAT IS THE REPOSITORY'S OWN CONVENTION, NOT A PREFERENCE. Seven authored registries live in
`engine/season/` and every one is YAML (`rosters`, `verb_table`, `write_matrix`, `requirements`,
`hole_register`, `ENDINGS_CLASSIFIED`, `venues`); the JSON artifacts all live under
`engine/engine_params/` and are all GENERATED, round-trip-checked, and port-facing. So: authored
source is YAML beside the code that reads it, and JSON is for what a machine consumes downstream.
A JSON roster here would be the only hand-edited JSON in the tree.

⚠ THE DERIVATION BECOMES A BOOTSTRAP, NOT A DEPENDENCY. After `--build`, `populated.py` reads the
roster and the matchers are no longer consulted at runtime. That is the whole point: a row a human
corrected must not be silently re-derived on the next run. Re-running `--build` REGENERATES and will
overwrite hand edits, which is why it is a deliberate command and not something the loop calls.

⚠ `--check` IS THE ROUND-TRIP, and it is the half that makes this a mechanism rather than a
snapshot. It re-derives from the cases and compares against the file, reporting every row that
differs. It does NOT fail on a difference: a hand-corrected home or tie is the roster working as
intended, and a gate that reddened on one would forbid the editing this file exists to allow. It
fails only when a row names a case that does not exist, or a place that does not.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import yaml

# ⚠ THE BOOTSTRAP IS A `sys.path.insert`, NEVER AN ASSIGNMENT, AND THE FIRST CUT OF THIS FILE GOT
# IT WRONG. It wrote `ROOT = Path(__file__).resolve().parents[1]` -- a fifty-fourth spelling of a
# primitive `tools/ci_common.py` has owned since plan G7 (ED-IN-0159 §8.1), which is the exact rule
# `CLAUDE.md` §8 states and which this tool's own commit message quoted. A module cannot import
# `ci_common` without first knowing where `ci_common` is, so the path insert is legitimate; the
# derived CONSTANT is not, and `tests/valoria/test_ci_common_primitives.py` is the guard that
# reddened on it.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ci_common import REPO, load_yaml  # noqa: E402

ROOT = Path(REPO)
ROSTER = ROOT / "engine" / "season" / "npcs.yaml"

HEADER = """# THE NPC ROSTER — who exists, where they live, what they want, who it concerns.
#
# GENERATED by `tools/export_npc_roster.py --build`, from `engine/season/cases/NPC*.yaml`.
# HAND-EDITABLE AFTER THAT, and that is the point of the file: correcting one NPC's home or tie is
# a one-row edit here rather than a change to a regular expression in a harness, where it would
# move other people silently.
#
# ⚠ RE-RUNNING `--build` OVERWRITES HAND EDITS. `--check` re-derives and REPORTS differences
# without failing on them, because a corrected row is this file working as intended. It fails only
# on a row naming a case or a place that does not exist.
#
# ⚠ THE NAMES AND THE WANTS ARE THE CORPUS'S, NOT AUTHORED HERE. `name` and `want` are read from
# the case; `want` is its first `core` row of `season_requires`. Inventing an NPC in this file
# would be exactly the fabrication `ED-WR-0011` (OI-05) is filed as a ruling to avoid — the engine
# declined to invent a world-gen NPC count rather than guess one, and this file does not get to
# guess either. Every row traces to a case id.
#
# FIELDS
#   case         the NPC case this person is  (`engine/season/cases/NPC*.yaml`)
#   name         the person's name, from the case
#   institution  which body they answer to, or null for an unaffiliated life
#   home         the building they are seated in  (`engine/season/venues.yaml`, canonical settlement)
#   want         what they want, in the case's own words
#   concerns     the case id of the person their want is about
#   tie          HOW that person was chosen: named | institution | roof | neighbour
"""


def derive() -> dict:
    """The roster as the matchers see it. One place, called by `--build` and by `--check`."""
    sys.path.insert(0, str(ROOT))
    from engine.season.harness import populated as POP

    w = POP.build_realm(0)
    geo, ven = POP._load(POP.GEOGRAPHY), POP._load(POP.VENUES)
    home_of, name_of = {}, {}
    for t in w.tenures:
        if t.kind == "contain" and t.live and t.subject in w.persons:
            home_of[t.subject] = t.object
    for pid, p in w.persons.items():
        name_of[pid] = p.name

    rows = []
    for case in POP.load_cases("NPC"):
        cid = str(case.get("id"))
        pid = f"p_{POP._slug(cid)}"
        if pid not in w.persons:
            continue
        prop = w.propositions.get(f"prop_{POP._slug(cid)}")
        concerns = None
        if prop is not None and prop.subject in w.persons:
            concerns = prop.subject[2:].upper().replace("_", "-")
        rows.append({
            "case": cid,
            "name": name_of[pid],
            "institution": POP.institution_of(case),
            "home": home_of.get(pid),
            "want": prop.predicate if prop is not None else None,
            "concerns": concerns,
        })
    return {"meta": {"source": "engine/season/cases/NPC*.yaml",
                     "generator": "tools/export_npc_roster.py",
                     "count": len(rows)},
            "npcs": rows}


def build() -> int:
    data = derive()
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100)
    ROSTER.write_text(HEADER + "\n" + body, encoding="utf-8")
    print(f"[npc-roster] wrote {ROSTER.relative_to(ROOT)} — {data['meta']['count']} NPCs")
    return 0


def check() -> int:
    if not ROSTER.exists():
        print(f"[npc-roster ✗] {ROSTER.relative_to(ROOT)} does not exist. Run --build.")
        return 1
    # `ci_common.load_yaml`, the intended owner. The residual count of bare loader calls in
    # `tools/` is pinned by `test_the_bare_yaml_load_residual_can_only_shrink` and may only go
    # DOWN; this call had no reason to bypass the owner, since the file is on disk and its absence
    # is already handled two lines up.
    # ⚠ THE GUARD COUNTS THE LITERAL TOKEN, so naming it even in a COMMENT raises the residual.
    # That is not a flaw worth fixing: a substring census is the only check that cannot be spelled
    # around, and the cost is that prose about the rule must avoid writing the rule's own name.
    on_disk = load_yaml(ROSTER)
    fresh = derive()
    sys.path.insert(0, str(ROOT))
    from engine.season.harness import populated as POP
    cases = {str(c.get("id")) for c in POP.load_cases("NPC")}
    w = POP.build_realm(0)

    hard = []
    for row in on_disk.get("npcs") or []:
        if row.get("case") not in cases:
            hard.append(f"{row.get('case')}: names no NPC case in the corpus")
        if row.get("home") and row["home"] not in w.rungs:
            hard.append(f"{row.get('case')}: home {row['home']!r} is not a rung in the world")
        if row.get("concerns") and f"p_{POP._slug(row['concerns'])}" not in w.persons:
            hard.append(f"{row.get('case')}: concerns {row['concerns']!r}, who is not seated")

    by_case = {r["case"]: r for r in (on_disk.get("npcs") or [])}
    drift = []
    for r in fresh["npcs"]:
        old = by_case.get(r["case"])
        if old is None:
            drift.append(f"{r['case']}: in the corpus, absent from the roster")
            continue
        for k in ("home", "institution", "concerns"):
            if old.get(k) != r.get(k):
                drift.append(f"{r['case']}.{k}: roster {old.get(k)!r} vs derived {r.get(k)!r}")

    if drift:
        print(f"[npc-roster] {len(drift)} row(s) differ from the derivation — REPORTED, NOT FAILED.")
        print("  A hand-corrected row is this file working as intended; a gate that reddened on")
        print("  one would forbid the editing the roster exists to allow.")
        for d in drift[:20]:
            print(f"    {d}")
        if len(drift) > 20:
            print(f"    … and {len(drift) - 20} more")
    if hard:
        print(f"[npc-roster ✗] {len(hard)} row(s) name something that does not exist:")
        for h in hard:
            print(f"    {h}")
        return 1
    print(f"[npc-roster ✓] every row names a real case, a real place and a seated person "
          f"({len(by_case)} NPCs)")
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--build", action="store_true", help="regenerate the roster (OVERWRITES edits)")
    ap.add_argument("--check", action="store_true", help="round-trip: report drift, fail on a dead reference")
    a = ap.parse_args(argv)
    if a.build:
        return build()
    return check()


if __name__ == "__main__":
    raise SystemExit(main())
