#!/usr/bin/env python3
"""
export_engine_params.py — typed engine-params export: the Godot-ingestible seed (ED-1052).

Serializes the CANONICAL personal-combat Class-C oracle
(designs/scene/combat_engine_v1/config.py — ratified ED-900/904; the live parameter source
per references/canonical_sources.yaml `resolution_engine`) to a typed JSON artifact:

    engine/engine_params/combat_engine_v1.json

WHY (CLAUDE.md §5): mechanical parameters live as prose tables a Godot importer cannot
ingest; every value crossing into Godot has been hand-transcribed (the ED-1050 failure
class: the port hand-"corrected" its oracle). This exporter starts the successor
discipline — oracle → typed export → port regenerates from the export, never hand-edits
(godot_conversion_strategy re-export rule; holonic doctrine ED-1083: convertibility =
round-trip morphisms). Scope guard: exports the ALREADY-TYPED Python oracle only; it does
NOT parse params/*.md prose (that pipeline remains future ED-1052 work).

MODES:
    python tools/export_engine_params.py            # (re)generate the JSON artifact
    python tools/export_engine_params.py --check    # re-derive and diff vs the committed
                                                    # file; exit 1 on ANY drift (value or
                                                    # shape). Blocking in CI: deterministic,
                                                    # self-consistent — if config.py changes,
                                                    # regenerate and commit both together.

The artifact is GENERATED — never hand-edit. Tuples become arrays; nested dicts pass
through; values are evaluated at import (computed expressions export their results).
`schema_version` bumps only on SHAPE changes (new/removed sections, type changes), not on
retuned values.
"""
import json
import os
import sys

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
ENGINE_DIR = os.path.join(REPO_ROOT, 'designs', 'scene', 'combat_engine_v1')
OUT_PATH = os.path.join(REPO_ROOT, 'engine', 'engine_params', 'combat_engine_v1.json')

SCHEMA_VERSION = 1


def _typed(value):
    """JSON-typed copy of a config value; tuples -> arrays, dicts recurse. Rejects types the
    schema doesn't declare (a new type is a shape change: bump SCHEMA_VERSION deliberately)."""
    if isinstance(value, bool) or isinstance(value, (int, float, str)):
        return value
    if isinstance(value, (list, tuple)):
        return [_typed(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _typed(v) for k, v in value.items()}
    raise TypeError(f"config value of unexported type {type(value).__name__}: {value!r}")


def derive():
    """Import the oracle and derive the export payload (deterministic)."""
    sys.path.insert(0, ENGINE_DIR)
    import config  # the Class-C oracle
    payload = {
        "_generated": ("GENERATED by tools/export_engine_params.py from "
                       "designs/scene/combat_engine_v1/config.py — the CANONICAL Class-C "
                       "combat oracle (ED-900/904; ED-1050 re-export discipline). NEVER "
                       "hand-edit: regenerate via the exporter and commit both together. "
                       "Class-C = calibrated against the harness, not canon prose."),
        "schema_version": SCHEMA_VERSION,
        "source": "designs/scene/combat_engine_v1/config.py",
        "canonical_status": "CANONICAL combat_engine_v1 (ED-900; re-ratified ED-904)",
        "sections": {
            "cfg": _typed(config.CFG),
            # handle_rank RETIRED (morphology-rearch Phase B6, 2026-07-02): config.HANDLE_RANK is gone —
            # systems.str_demand reads weapon_physics.handling() (real per-part data) instead.
        },
    }
    return payload


def render(payload):
    return json.dumps(payload, indent=1, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv):
    payload = render(derive())
    if '--check' in argv:
        try:
            with open(OUT_PATH, encoding='utf-8') as f:
                committed = f.read()
        except OSError:
            print(f"[DRIFT] {os.path.relpath(OUT_PATH, REPO_ROOT)} missing — run the exporter and commit it.")
            return 1
        if committed != payload:
            print("[DRIFT] committed engine-params JSON does not match config.py.")
            print("        config.py changed without re-export (or the JSON was hand-edited).")
            print("        Fix: python tools/export_engine_params.py  && commit both files together.")
            return 1
        print("Engine-params round-trip: committed JSON matches config.py (oracle -> export verified).")
        return 0
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write(payload)
    print(f"Wrote {os.path.relpath(OUT_PATH, REPO_ROOT)} "
          f"(schema v{SCHEMA_VERSION}; {len(json.loads(payload)['sections']['cfg'])} cfg keys).")
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
