"""
index_gen.py — Generate index files for registers, archives, and atomized file sets.

Pure functions: no GitHub I/O. Caller provides content, receives index strings.
All indexes are regenerable from authoritative source. Never hand-edit indexes.
"""

import re
import yaml
from datetime import datetime, timezone


def generate_patch_index(active_yaml: str, archive_yamls: dict[str, str] = None) -> str:
    """
    Scan all PP entries across active + archives.
    Emit compact index: ID | system | status | date | description.
    """
    entries = _collect_pp_entries(active_yaml, archive_yamls or {})
    lines = [
        "# Patch Register Index",
        "",
        f"<!-- auto-generated by index_gen.py — {_now()} -->",
        f"<!-- total entries: {len(entries)} -->",
        "",
        "| ID | Status | System | Date | Description |",
        "|----|--------|--------|------|-------------|",
    ]
    for e in sorted(entries, key=lambda x: x['id_num']):
        lines.append(
            f"| {e['id']} | {e['status']} | {e['system']} | {e['date']} | {e['desc']} |"
        )
    return "\n".join(lines) + "\n"


def generate_editorial_index(active_yaml: str, archive_yamls: dict[str, str] = None) -> str:
    """Compact index for ED-NNN entries."""
    entries = _collect_ed_entries(active_yaml, archive_yamls or {})
    lines = [
        "# Editorial Ledger Index",
        "",
        f"<!-- auto-generated by index_gen.py — {_now()} -->",
        f"<!-- total entries: {len(entries)} -->",
        "",
        "| ID | Status | Priority | System | Description |",
        "|----|--------|----------|--------|-------------|",
    ]
    for e in sorted(entries, key=lambda x: x['id_num']):
        lines.append(
            f"| {e['id']} | {e['status']} | {e['priority']} | {e['system']} | {e['desc']} |"
        )
    return "\n".join(lines) + "\n"


def generate_editorial_summary(active_yaml: str) -> str:
    """
    Very compact summary of active editorials.
    Target: max 1000 tokens per rule.
    """
    entries = _collect_ed_entries(active_yaml)

    open_entries = [e for e in entries if e['status'] in ('open', 'proposed', 'provisional')]
    p1 = [e for e in open_entries if e['priority'] == 'P1-BLOCKER']
    p2 = [e for e in open_entries if e['priority'] == 'P2']

    recent_resolved = [e for e in entries if e['status'] == 'resolved']
    recent_resolved.sort(key=lambda x: x['id_num'], reverse=True)
    recent_resolved = recent_resolved[:5]

    lines = [
        f"# Editorial Ledger Summary",
        f"",
        f"<!-- auto-generated by index_gen.py — {_now()} -->",
        f"",
        f"p1_blocker_count: {len(p1)}",
        f"open_count: {len(open_entries)}",
        f"total_active: {len(entries)}",
        f"next_id: {max((e['id_num'] for e in entries), default=0) + 1}",
        f"",
        f"p1_blockers:",
    ]
    for e in p1:
        lines.append(f"  - {e['id']}: {e['desc']}")
    if not p1:
        lines.append("  - none")

    lines.append(f"")
    lines.append(f"p2_open:")
    for e in p2[:10]:  # cap at 10 to stay compact
        lines.append(f"  - {e['id']}: {e['desc']}")
    if not p2:
        lines.append("  - none")

    lines.append(f"")
    lines.append(f"recent_resolutions:")
    for e in recent_resolved:
        lines.append(f"  - {e['id']}: {e['desc']}")
    if not recent_resolved:
        lines.append("  - none")

    return "\n".join(lines) + "\n"


def generate_archive_chunks_index(chunk_files: dict[str, str], pattern: str = "") -> str:
    """
    For atomized archives: list of chunk files with ID ranges.
    Example: patch_register_archive_001_200.yaml → PP-001..PP-200
    """
    lines = [
        "# Archive Chunks Index",
        "",
        f"<!-- auto-generated by index_gen.py — {_now()} -->",
        "",
        "| Chunk File | ID Range | Entries |",
        "|------------|----------|---------|",
    ]
    for path in sorted(chunk_files.keys()):
        content = chunk_files[path]
        # Count entries
        ids = re.findall(r'(PP-\d+|ED-\d+)', content)
        unique_ids = sorted(set(ids))
        if unique_ids:
            range_str = f"{unique_ids[0]}..{unique_ids[-1]}"
        else:
            range_str = "empty"
        lines.append(f"| {path} | {range_str} | {len(unique_ids)} |")

    return "\n".join(lines) + "\n"


def generate_atomized_file_index(domain_files: dict[str, str], source: str) -> str:
    """
    For atomized params files: TOC of which domain file contains which headings.
    Becomes the content of the file at the original path (index_replaces_canonical).
    """
    lines = [
        f"# {source.rsplit('/', 1)[-1]} — Index",
        "",
        f"<!-- auto-generated by index_gen.py — {_now()} -->",
        f"<!-- This file replaces the monolithic original. Domain files contain the actual content. -->",
        "",
    ]
    for path in sorted(domain_files.keys()):
        content = domain_files[path]
        # Extract headings
        headings = re.findall(r'^(#{1,3})\s+(.+)', content, re.MULTILINE)
        tokens = len(content) // 4
        lines.append(f"## [{path.rsplit('/', 1)[-1]}]({path})")
        lines.append(f"")
        lines.append(f"~{tokens:,} tokens")
        lines.append(f"")
        for level, text in headings[:15]:  # cap listing per file
            indent = "  " * (len(level) - 1)
            lines.append(f"{indent}- {text.strip()}")
        if len(headings) > 15:
            lines.append(f"  ... +{len(headings) - 15} more headings")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_session_archive_index(chunk_files: dict[str, str]) -> str:
    """For session_log_archive_YYYY_qN.md chunks."""
    lines = [
        "# Session Log Archive Index",
        "",
        f"<!-- auto-generated by index_gen.py — {_now()} -->",
        "",
        "| Chunk | Sessions | Period |",
        "|-------|----------|--------|",
    ]
    for path in sorted(chunk_files.keys()):
        content = chunk_files[path]
        session_ids = re.findall(r'session_id:\s*(.+)', content)
        dates = re.findall(r'session_close:\s*(\d{4}-\d{2}-\d{2})', content)
        period = f"{dates[0]}..{dates[-1]}" if dates else "unknown"
        lines.append(f"| {path} | {len(session_ids)} | {period} |")

    return "\n".join(lines) + "\n"


# ── Internal helpers ──────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _collect_pp_entries(active_yaml: str, archive_yamls: dict[str, str] = None) -> list:
    """Parse PP entries from active + archive YAML files."""
    entries = []
    for source_content in [active_yaml] + list((archive_yamls or {}).values()):
        if not source_content:
            continue
        try:
            data = yaml.safe_load(source_content)
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        for key, val in data.items():
            m = re.match(r'(PP-\d+)', str(key))
            if not m:
                continue
            if not isinstance(val, dict):
                continue
            pp_id = m.group(1)
            id_num = int(re.search(r'\d+', pp_id).group())
            entries.append({
                'id': pp_id,
                'id_num': id_num,
                'status': str(val.get('status', 'unknown')),
                'system': str(val.get('system', '')),
                'date': str(val.get('date', '')),
                'desc': _truncate(str(val.get('description', val.get('desc', ''))), 60),
            })
    return entries


def _collect_ed_entries(active_yaml: str, archive_yamls: dict[str, str] = None) -> list:
    """Parse ED entries from active + archive YAML files."""
    entries = []
    for source_content in [active_yaml] + list((archive_yamls or {}).values()):
        if not source_content:
            continue
        try:
            data = yaml.safe_load(source_content)
        except Exception:
            continue
        if not isinstance(data, dict):
            continue
        for key, val in data.items():
            m = re.match(r'(ED-\d+)', str(key))
            if not m:
                continue
            if not isinstance(val, dict):
                continue
            ed_id = m.group(1)
            id_num = int(re.search(r'\d+', ed_id).group())
            entries.append({
                'id': ed_id,
                'id_num': id_num,
                'status': str(val.get('status', 'unknown')),
                'priority': str(val.get('priority', '')),
                'system': str(val.get('system', '')),
                'desc': _truncate(str(val.get('description', val.get('desc', ''))), 60),
            })
    return entries


def _truncate(s: str, max_len: int) -> str:
    s = s.replace("\n", " ").strip()
    if len(s) <= max_len:
        return s
    return s[:max_len - 3] + "..."


# ── CLI test ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    sample_ed = """
ED-001:
  status: resolved
  priority: P2
  system: threadwork
  description: Test editorial 1
ED-002:
  status: open
  priority: P1-BLOCKER
  system: board_game
  description: Test blocker
"""
    print("=== Editorial Index ===")
    print(generate_editorial_index(sample_ed))
    print("=== Editorial Summary ===")
    print(generate_editorial_summary(sample_ed))
