#!/usr/bin/env python3
"""Join an audit unit's nested working papers into one document, so the excess can be purged.

WHY.

Jordan, 2026-08-04, on the audit corpus: *"we can keep the nested working papers so long as they
are filed very cleanly or we can join them all together and purge the excess"*, and on the one
unit the lane rule over-captured: *"emergent narrative to be kept but joined appropriately"*.

The shape of the problem, measured: an audit unit is a head document plus a nested tier of drafts,
refutes, judge passes and spec fragments. Across the July corpus, 278 of 493 kept `.md` sat at
depth >= 2 — the working tier outnumbered the findings roughly 4:3, and a large fraction declare
themselves SUPERSEDED in their own `## Status:` line. That tier is not worthless (it is the
reasoning behind a finding, and Jordan wants the continuity) but it does not need to be 46 files.

WHAT "JOINED" MEANS HERE, precisely, because a merge that loses content is a deletion wearing a
nicer word. This concatenates every nested `.md` of a unit into ONE `_workings_joined.md` at the
unit root, in sorted path order, each fragment preceded by a machine-readable delimiter carrying
its original path. The fragment text is copied VERBATIM — bytes in, bytes out, no reflow, no
heading renumbering, no summarisation. Nothing is interpreted, so nothing can be misinterpreted.

THE GUARANTEE, and how it is checked rather than asserted: `--check` re-splits the joined file on
its own delimiters and compares each recovered fragment against the source bytes. `--verify-only`
does the same against an already-purged unit using the joined file alone, which is the state that
actually matters — after the fragments are gone, the joined file IS the archive, and the only
useful question is whether it can still be taken apart. `tests/valoria/test_join_audit_workings.py`
carries the round-trip and its positive controls.

ORDER OF OPERATIONS is not negotiable: join, verify, THEN purge. The tool will not purge a unit
whose join does not round-trip, and it never purges without `--purge` being asked for explicitly.

Usage:
    python3 tools/join_audit_workings.py --list
    python3 tools/join_audit_workings.py --unit audit/2026-07-05-emergent-narrative-engine
    python3 tools/join_audit_workings.py --unit <u> --purge     # join, verify, then delete parts
    python3 tools/join_audit_workings.py --check                # every joined unit round-trips
"""
from __future__ import annotations

import argparse
import os
import sys

# Primitives (repo root, lane roster, token estimate, ids, Status reader) are
# owned by tools/ci_common.py — plan G7, ED-IN-0159 §8.3. See its module docstring;
# the two lines below are the bootstrap, anchored on THIS file's directory.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ci_common  # noqa: E402

REPO = ci_common.REPO
JOINED_NAME = '_workings_joined.md'

# The delimiter. Chosen to be (a) unmistakable, (b) illegal as ordinary prose, (c) parseable by an
# exact string match rather than a regex — a regex here would be one more thing that can be subtly
# wrong about content it is meant to preserve untouched.
BEGIN = '<!-- VALORIA-JOINED-FRAGMENT BEGIN: {path} -->'
END = '<!-- VALORIA-JOINED-FRAGMENT END: {path} -->'

HEADER = """<!--
GENERATED by tools/join_audit_workings.py. NEVER hand-edit a fragment body: edit the source and
re-join, or if the sources are purged, treat this file as the archive of record.

This is a VERBATIM concatenation of the working papers of one audit unit — drafts, refutes, judge
passes, spec fragments — joined so the unit could keep its reasoning without keeping N files
(Jordan, 2026-08-04: "we can join them all together and purge the excess"). Each fragment sits
between BEGIN/END delimiters carrying its original path, and `--check` re-splits on those
delimiters and compares against source bytes, so the join is reversible rather than merely tidy.

Nothing was summarised, reflowed or renumbered. A fragment's `## Status:` line still describes the
FRAGMENT, not this file.
-->

# {unit} — joined working papers

{count} fragment(s), joined in sorted path order.

"""


def unit_root(unit: str) -> str:
    return os.path.join(REPO, unit)


def fragments(unit: str, include_top: bool = False) -> list[str]:
    """`.md` of the unit to join. Sorted, repo-relative.

    DEFAULT — nested only. The unit's TOP-LEVEL files are the findings and stay where a reader
    expects them; only the working tier joins. That boundary is the one the corpus already draws.

    `include_top` — EVERY `.md`, top level included. Jordan, 2026-08-04, on the contest gate
    packets: *"contest gate packets like social contest or whatever get joined if multiple mds and
    retained"*. Those units are small multi-document packets with no nested tier at all, so the
    default mode finds nothing to join. Retained either way; this only reduces the file count.

    Non-markdown files are NEVER touched, in either mode. Jordan, same day: *"keep them if their
    accompanying audit directories are being kept in main"* — a kept unit keeps its JSON.
    """
    root = unit_root(unit)
    out = []
    for dirpath, _dirnames, filenames in os.walk(root):
        at_top = os.path.abspath(dirpath) == os.path.abspath(root)
        if at_top and not include_top:
            continue
        for name in filenames:
            if name.endswith('.md') and name != JOINED_NAME:
                out.append(os.path.relpath(os.path.join(dirpath, name), REPO).replace(os.sep, '/'))
    return sorted(out)


def _read(rel: str) -> str:
    # bytes + strict decode, for the reason ED-IN-0139 F1 records: a lossy read on both sides of a
    # comparison makes the comparison agree with itself instead of with the file.
    with open(os.path.join(REPO, rel), 'rb') as fh:
        return fh.read().decode('utf-8')


def join(unit: str, include_top: bool = False) -> tuple[str, list[str]]:
    frags = fragments(unit, include_top)
    parts = [HEADER.format(unit=unit, count=len(frags))]
    for rel in frags:
        parts.append(BEGIN.format(path=rel) + '\n')
        parts.append(_read(rel))
        parts.append('\n' + END.format(path=rel) + '\n\n')
    return ''.join(parts), frags


def split(text: str) -> dict[str, str]:
    """Recover {path: body} from a joined document. The inverse of `join`, by exact delimiters."""
    out, pos = {}, 0
    while True:
        b = text.find('<!-- VALORIA-JOINED-FRAGMENT BEGIN: ', pos)
        if b == -1:
            return out
        path_start = b + len('<!-- VALORIA-JOINED-FRAGMENT BEGIN: ')
        path_end = text.index(' -->', path_start)
        rel = text[path_start:path_end]
        body_start = text.index('\n', path_end) + 1
        end_marker = '\n' + END.format(path=rel) + '\n'
        body_end = text.index(end_marker, body_start)
        out[rel] = text[body_start:body_end]
        pos = body_end + len(end_marker)


def verify(unit: str, against_sources: bool = True, include_top: bool = False) -> list[str]:
    """Round-trip the joined file. Returns a list of problems; empty means it is reversible."""
    joined_path = os.path.join(unit_root(unit), JOINED_NAME)
    if not os.path.exists(joined_path):
        return [f'{unit}: no {JOINED_NAME}']
    with open(joined_path, 'rb') as fh:
        recovered = split(fh.read().decode('utf-8'))
    if not recovered:
        return [f'{unit}: {JOINED_NAME} contains no recoverable fragment — the join is inert']
    problems = []
    if against_sources:
        srcs = fragments(unit, include_top)
        for rel in srcs:
            if rel not in recovered:
                problems.append(f'{unit}: {rel} missing from the join')
            elif recovered[rel].encode('utf-8') != open(os.path.join(REPO, rel), 'rb').read():
                problems.append(f'{unit}: {rel} does not round-trip byte-exactly')
        for rel in recovered:
            if rel not in srcs and os.path.exists(os.path.join(REPO, rel)):
                problems.append(f'{unit}: {rel} is in the join but not in the source set')
    return problems


def joined_units() -> list[str]:
    out = []
    for dirpath, _dirnames, filenames in os.walk(os.path.join(REPO, 'audit')):
        if JOINED_NAME in filenames:
            out.append(os.path.relpath(dirpath, REPO).replace(os.sep, '/'))
    return sorted(out)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument('--unit', help='audit/<session> to join')
    ap.add_argument('--purge', action='store_true',
                    help='after a VERIFIED join, delete the fragment files')
    ap.add_argument('--check', action='store_true',
                    help='every already-joined unit still round-trips (CI mode)')
    ap.add_argument('--list', action='store_true', help='units with a nested working tier')
    ap.add_argument('--include-top', action='store_true',
                    help='join EVERY .md of the unit, top level included (gate-packet mode)')
    args = ap.parse_args(argv)

    if args.list:
        import collections
        counts = collections.Counter()
        for dirpath, _d, filenames in os.walk(os.path.join(REPO, 'audit')):
            rel = os.path.relpath(dirpath, REPO).replace(os.sep, '/')
            parts = rel.split('/')
            if len(parts) > 2:
                counts['/'.join(parts[:2])] += sum(1 for n in filenames if n.endswith('.md'))
        for u, n in counts.most_common():
            print(f'  {n:4d}  {u}')
        print(f'{len(counts)} unit(s) with a nested tier, {sum(counts.values())} working paper(s)')
        return 0

    if args.check:
        units = joined_units()
        if not units:
            print('[join] no joined units — nothing to check')
            return 0
        bad = []
        for u in units:
            # sources may already be purged; verify what is verifiable
            bad += verify(u, against_sources=bool(fragments(u)))
        if bad:
            print(f'[join] {len(bad)} problem(s):')
            for b in bad:
                print(f'        {b}')
            return 1
        print(f'[join] OK — {len(units)} joined unit(s) round-trip')
        return 0

    if not args.unit:
        ap.error('--unit, --check or --list required')
    unit = args.unit.rstrip('/')
    frags = fragments(unit, args.include_top)
    if len(frags) < 2:
        print(f'[join] {unit}: {len(frags)} joinable .md — nothing to join')
        return 1
    text, _ = join(unit, args.include_top)
    out = os.path.join(unit_root(unit), JOINED_NAME)
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write(text)
    print(f'[join] wrote {os.path.relpath(out, REPO)} — {len(frags)} fragment(s)')

    problems = verify(unit, include_top=args.include_top)
    if problems:
        print(f'[join] REFUSING TO PURGE — {len(problems)} round-trip problem(s):')
        for p in problems:
            print(f'        {p}')
        return 1
    print(f'[join] round-trip verified: all {len(frags)} fragment(s) recover byte-exactly')

    if args.purge:
        for rel in frags:
            os.remove(os.path.join(REPO, rel))
        # clean up directories the purge emptied
        for dirpath, dirnames, filenames in os.walk(unit_root(unit), topdown=False):
            if not dirnames and not filenames:
                os.rmdir(dirpath)
        print(f'[join] purged {len(frags)} fragment(s); {JOINED_NAME} is now the archive of record')
    else:
        print('[join] not purging (pass --purge). The fragments are still on disk.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
