#!/usr/bin/env python3
"""vocab_store.py — the vocabulary fold (Repository State Armature Phase 3, ED-IN-0078).

Overturns the ED-IN-0029 frozen-keep: the vocabulary registers become GENERATED VIEWS of one
source (`references/definitions/vocab_source.yaml`) instead of separate hand-maintained files.
Same "views at existing paths" pattern as the Phase-2 definitions store — no reader is rewired:
each register is regenerated at its existing path, so the sole live consumer (the report-only
`tools/observability/build_lexicon.py`) keeps reading the same paths.

Slice 2 folds the four registers `build_lexicon` reads by DATA FIELD only (a YAML-dump view is
faithful): alias_registry, deprecated_terms_registry, censured_vocabulary, synonym_registry.
name_collision_database is NOT folded here — `build_lexicon` parses its inline `# COLLISION`
comments by raw line, which a YAML dump would drop; it lands in Slice 3 with a coordinated
build_lexicon change (comment → data field).

CLI:
  python3 tools/vocab_store.py --seed    # (one-time) build vocab_source.yaml FROM the current registers
  python3 tools/vocab_store.py --build    # regenerate the register views FROM vocab_source.yaml
  python3 tools/vocab_store.py --check     # parity gate: committed views == fresh rebuild (exit 1 on drift)
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "references" / "definitions" / "vocab_source.yaml"

# register key -> its path. Only DATA-field-read registers (build_lexicon-safe under a YAML dump).
REGISTERS = {
    "alias_registry": ROOT / "references" / "alias_registry.yaml",
    "deprecated_terms_registry": ROOT / "references" / "deprecated_terms_registry.yaml",
    "censured_vocabulary": ROOT / "references" / "censured_vocabulary.yaml",
    "synonym_registry": ROOT / "references" / "synonym_registry.yaml",
    # Slice 3 (ED-IN-0078): name_collision_database's former inline `# COLLISION` comments were
    # migrated to a per-abbreviation `note:` data field (build_lexicon now reads that field), so a
    # YAML-dump view is faithful and this register folds in like the rest.
    "name_collision_database": ROOT / "references" / "name_collision_database.yaml",
}

_SRC_HEADER = """\
# vocab_source.yaml — the single source for the folded vocabulary registers (ED-IN-0078, Phase 3).
# Each top-level key under `registers:` is the authoritative data for one register; the register
# files at references/*.yaml are GENERATED views of these blocks (tools/vocab_store.py --build).
# Edit vocab data HERE, then --build. Drift-locked by `--check`.
"""


def _view_header(name: str) -> str:
    return (f"# GENERATED by tools/vocab_store.py --build from references/definitions/vocab_source.yaml\n"
            f"# — DO NOT EDIT BY HAND (ED-IN-0078, Phase 3 vocab fold). Source key: registers.{name}\n")


def seed() -> None:
    """One-time: read the current register files, write vocab_source.yaml carrying their data."""
    registers = {}
    for name, path in REGISTERS.items():
        registers[name] = yaml.safe_load(path.read_text(encoding="utf-8"))
    payload = {"version": 1, "registers": registers}
    SOURCE.parent.mkdir(parents=True, exist_ok=True)
    SOURCE.write_text(_SRC_HEADER + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100))


def _render(name: str, data) -> str:
    return _view_header(name) + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100)


def _load_source() -> dict:
    return (yaml.safe_load(SOURCE.read_text(encoding="utf-8")) or {}).get("registers", {})


def build() -> list[str]:
    """Regenerate every register view from the source. Returns the paths written."""
    regs = _load_source()
    written = []
    for name, path in REGISTERS.items():
        if name not in regs:
            continue
        path.write_text(_render(name, regs[name]), encoding="utf-8")
        written.append(str(path.relative_to(ROOT)))
    return written


def check() -> tuple[bool, list[str]]:
    """Parity gate: every committed register view must equal a fresh render from the source."""
    if not SOURCE.exists():
        return False, ["vocab_source.yaml missing — run `vocab_store.py --seed`"]
    regs = _load_source()
    msgs, ok = [], True
    for name, path in REGISTERS.items():
        if name not in regs:
            msgs.append(f"source missing register block: {name}"); ok = False; continue
        if not path.exists():
            msgs.append(f"view missing: {path.relative_to(ROOT)}"); ok = False; continue
        if path.read_text(encoding="utf-8") != _render(name, regs[name]):
            msgs.append(f"DRIFT: {path.relative_to(ROOT)} != fresh render — run --build and commit"); ok = False
    return ok, msgs


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", action="store_true")
    ap.add_argument("--build", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    if args.seed:
        seed(); print(f"seeded {SOURCE.relative_to(ROOT)} from {len(REGISTERS)} registers"); return 0
    if args.build:
        w = build(); print(f"regenerated {len(w)} register view(s): {', '.join(w)}"); return 0
    if args.check:
        ok, msgs = check()
        for m in msgs:
            print("  - " + m, file=sys.stderr)
        print("[VOCAB] views current — parity holds" if ok else "[VOCAB] FAILED", file=sys.stderr if not ok else sys.stdout)
        return 0 if ok else 1
    print(__doc__); return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
